import { createContext } from "react";

export type Language = "en" | "ar";

export interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  isRTL: boolean;
}

export const translations: Record<string, Record<Language, string>> = {
  // Navbar
  "nav.contact": { en: "Contact Us", ar: "تواصل معنا" },
  "nav.aljadriya": { en: "AL-JADRIYA", ar: "الجادرية" },
  "nav.engineering": { en: "Engineering", ar: "للهندسة" },

  // Hero slides (new format)
  "hero.slide1.label": { en: "COMMITTED TO THE FUTURE OF ENGINEERING & EDUCATION", ar: "ملتزمون بمستقبل الهندسة والتعليم" },
  "hero.slide1.heading": { en: "THIS IS\nAL-JADRIYA", ar: "هذه هي\nالجادرية" },
  "hero.slide1.tab": { en: "Energy", ar: "الطاقة" },
  "hero.slide2.label": { en: "ROBOTICS & AI", ar: "الروبوتات والذكاء الاصطناعي" },
  "hero.slide2.heading": { en: "Shaping the\nNext Generation", ar: "نصنع\nالجيل القادم" },
  "hero.slide2.tab": { en: "Robotics", ar: "الروبوتات" },
  "hero.slide3.label": { en: "MEDICAL ENGINEERING", ar: "الهندسة الطبية" },
  "hero.slide3.heading": { en: "Engineering Better\nHealthcare", ar: "هندسة رعاية\nصحية أفضل" },
  "hero.slide3.tab": { en: "Medical", ar: "الطبية" },
  "hero.slide4.label": { en: "OIL & GAS INFRASTRUCTURE", ar: "بنية النفط والغاز التحتية" },
  "hero.slide4.heading": { en: "Built for the Field.\nEngineered to Last.", ar: "بُنيت للميدان.\nصُممت لتدوم." },
  "hero.slide4.tab": { en: "Oil & Gas", ar: "النفط والغاز" },
  "hero.learnMore": { en: "Learn More", ar: "اعرف المزيد" },
  "hero.scrollDown": { en: "Scroll Down", ar: "مرر للأسفل" },

  // About Section
  "about.label": { en: "Welcome to AL-JADRIYA Engineering", ar: "مرحباً بكم في الجادرية للهندسة" },
  "about.heading": { en: "Leading in engineering, education, and innovation", ar: "رائدون في الهندسة والتعليم والابتكار" },
  "about.text": { en: "We are an integrated engineering and educational technology company, serving Jordan, Iraq, and the wider region. From complex engineering consultancy to world-class AI and robotics training programs, we build the future on two fronts.", ar: "نحن شركة هندسية وتكنولوجيا تعليمية متكاملة، نخدم الأردن والعراق والمنطقة الأوسع. من الاستشارات الهندسية المعقدة إلى برامج تدريب الذكاء الاصطناعي والروبوتات على مستوى عالمي، نبني المستقبل على جبهتين." },
  "about.stat1.number": { en: "2", ar: "٢" },
  "about.stat1.label": { en: "Specialized Divisions", ar: "أقسام متخصصة" },
  "about.stat2.number": { en: "2", ar: "٢" },
  "about.stat2.label": { en: "Countries: Jordan & Iraq", ar: "الدول: الأردن والعراق" },
  "about.stat3.number": { en: "6", ar: "٦" },
  "about.stat3.label": { en: "Regional Markets", ar: "أسواق إقليمية" },
  "about.stat4.number": { en: "101+", ar: "+١٠١" },
  "about.stat4.label": { en: "Projects & Programs Delivered", ar: "مشاريع وبرامج منجزة" },

  // Values Section
  "values.heading": { en: "VALUES", ar: "قيمنا" },
  "values.1": { en: "Operational excellence", ar: "التميز التشغيلي" },
  "values.2": { en: "Tireless experimentation for innovative business solutions", ar: "التجريب الدؤوب لحلول أعمال مبتكرة" },
  "values.3": { en: "Open and respectful working environment", ar: "بيئة عمل منفتحة ومحترمة" },
  "values.4": { en: "Trustworthiness in all business relationships", ar: "الموثوقية في جميع العلاقات التجارية" },
  "values.5": { en: "Highest ethical standards", ar: "أعلى المعايير الأخلاقية" },
  "values.6": { en: "Sustainable financial strength", ar: "قوة مالية مستدامة" },

  // Divisions Section
  "divisions.heading": { en: "Our Divisions & Services", ar: "أقسامنا وخدماتنا" },
  "divisions.learnMore": { en: "Learn More", ar: "اعرف المزيد" },
  "divisions.1.title": { en: "Engineering Consultancy Division", ar: "قسم الاستشارات الهندسية" },
  "divisions.1.desc": { en: "Comprehensive engineering consultancy across medical facilities, industrial pipelines, infrastructure, and turnkey projects, serving public and private sector clients across Jordan and Iraq.", ar: "استشارات هندسية شاملة عبر المرافق الطبية وخطوط الأنابيب الصناعية والبنية التحتية والمشاريع المتكاملة، لخدمة عملاء القطاعين العام والخاص في الأردن والعراق." },
  "divisions.2.title": { en: "Educational Technology Division", ar: "قسم التكنولوجيا التعليمية" },
  "divisions.2.desc": { en: "World-class robotics, programming, and AI training programs delivered to schools, professionals, and career-shifters, in-person and online.", ar: "برامج تدريب روبوتات وبرمجة وذكاء اصطناعي على مستوى عالمي تُقدم للمدارس والمهنيين والمتحولين مهنياً، حضورياً وعبر الإنترنت." },
  "divisions.3.title": { en: "Equipment Supply & Tenders", ar: "توريد المعدات والمناقصات" },
  "divisions.3.desc": { en: "Full capability to supply technical equipment, manage government tenders, and place trained graduates into the workforce.", ar: "قدرة كاملة على توريد المعدات التقنية وإدارة المناقصات الحكومية وتوظيف الخريجين المدربين." },
  "divisions.4.title": { en: "International Partnerships", ar: "الشراكات الدولية" },
  "divisions.4.desc": { en: "Backed by established relationships with leading international partners, operating across Jordan, Iraq, UAE, KSA, Egypt, and Libya.", ar: "مدعومة بعلاقات راسخة مع شركاء دوليين رائدين، تعمل عبر الأردن والعراق والإمارات والسعودية ومصر وليبيا." },

  // Finder Section
  "finder.label": { en: "Find the right solution for your needs", ar: "اعثر على الحل المناسب لاحتياجاتك" },
  "finder.heading": { en: "I'm looking for", ar: "أبحث عن" },
  "finder.cta": { en: "Explore Solutions", ar: "استكشف الحلول" },
  "finder.sol1": { en: "engineering consultancy", ar: "استشارات هندسية" },
  "finder.sol2": { en: "robotics training programs", ar: "برامج تدريب الروبوتات" },
  "finder.sol3": { en: "AI workforce solutions", ar: "حلول القوى العاملة بالذكاء الاصطناعي" },
  "finder.sol4": { en: "project management", ar: "إدارة المشاريع" },
  "finder.sol5": { en: "equipment supply", ar: "توريد المعدات" },

  // Vision Section
  "vision.heading": { en: "Our Vision for the Region", ar: "رؤيتنا للمنطقة" },
  "vision.text": { en: "Since its founding, AL-JADRIYA Engineering has been guided by a firm philosophy: a company's greatest asset is the trust it builds with its clients, partners, trainees, and community. We aim to be the most trusted engineering and education provider in the Middle East.", ar: "منذ تأسيسها، تسترشد الجادرية للهندسة بفلسفة راسخة: أعظم أصول الشركة هي الثقة التي تبنيها مع عملائها وشركائها ومتدربيها ومجتمعها. نسعى لأن نكون أكثر مزودي الهندسة والتعليم ثقةً في الشرق الأوسط." },
  "vision.cta": { en: "Learn More", ar: "اعرف المزيد" },

  // Footer
  "footer.offices": { en: "Our Offices", ar: "مكاتبنا" },
  "footer.amman": { en: "Amman, Jordan", ar: "عمّان، الأردن" },
  "footer.hq": { en: "Headquarters", ar: "المقر الرئيسي" },
  "footer.baghdad": { en: "Baghdad, Iraq", ar: "بغداد، العراق" },
  "footer.branch": { en: "Branch Office", ar: "مكتب فرعي" },
  "footer.email": { en: "Email", ar: "البريد الإلكتروني" },
  "footer.helpTitle": { en: "Here to help you", ar: "هنا لمساعدتك" },
  "footer.helpText": { en: "Any questions? We'd love to hear from you.", ar: "أي أسئلة؟ يسعدنا سماعك." },
  "footer.contact": { en: "Contact Us", ar: "تواصل معنا" },
  "footer.terms": { en: "Terms & Conditions", ar: "الشروط والأحكام" },
  "footer.privacy": { en: "Privacy Policy", ar: "سياسة الخصوصية" },
  
  "footer.engConsultancy": { en: "Engineering Consultancy", ar: "الاستشارات الهندسية" },
  "footer.eduTech": { en: "Educational Technology", ar: "التكنولوجيا التعليمية" },
  "footer.equipSupply": { en: "Equipment Supply", ar: "توريد المعدات" },
  "footer.aboutUs": { en: "About Us", ar: "من نحن" },

  // MegaMenu (legacy keys kept for compatibility)
  "menu.engConsultancy": { en: "Engineering Consultancy", ar: "الاستشارات الهندسية" },
  "menu.eduTech": { en: "Educational Technology", ar: "التكنولوجيا التعليمية" },
  "menu.equipSupply": { en: "Equipment Supply", ar: "توريد المعدات" },
  "menu.aboutUs": { en: "About Us", ar: "من نحن" },
  "menu.contactUs": { en: "Contact Us", ar: "تواصل معنا" },
  "menu.projectPlanning": { en: "Project Planning", ar: "تخطيط المشاريع" },
  "menu.feasibilityStudies": { en: "Feasibility Studies", ar: "دراسات الجدوى" },
  "menu.medicalEngConsultancy": { en: "Medical Engineering Consultancy", ar: "استشارات الهندسة الطبية" },
  "menu.technicalDesign": { en: "Technical Design", ar: "التصميم التقني" },
  "menu.procurement": { en: "Procurement", ar: "المشتريات" },
  "menu.turnkeyProjects": { en: "Turnkey Projects", ar: "مشاريع متكاملة" },
  "menu.siteSurveys": { en: "Site Surveys", ar: "المسح الميداني" },
  "menu.roboticsPrograms": { en: "Robotics Programs", ar: "برامج الروبوتات" },
  "menu.aiTraining": { en: "AI Training", ar: "تدريب الذكاء الاصطناعي" },
  "menu.schoolPartnerships": { en: "School Partnerships", ar: "شراكات المدارس" },
  "menu.onlineCourses": { en: "Online Courses", ar: "دورات عبر الإنترنت" },
  "menu.corporateTraining": { en: "Corporate Training", ar: "تدريب الشركات" },
  "menu.industrialEquipment": { en: "Industrial Equipment", ar: "معدات صناعية" },
  "menu.medicalEquipment": { en: "Medical Equipment", ar: "معدات طبية" },
  "menu.educationalTechnology": { en: "Educational Technology", ar: "تكنولوجيا تعليمية" },
  "menu.constructionMaterials": { en: "Construction Materials", ar: "مواد البناء" },
  "menu.tenderManagement": { en: "Tender Management", ar: "إدارة المناقصات" },
  "menu.afterSalesSupport": { en: "After-Sales Support", ar: "دعم ما بعد البيع" },
  "menu.ourStory": { en: "Our Story", ar: "قصتنا" },
  "menu.leadership": { en: "Leadership", ar: "القيادة" },
  "menu.careers": { en: "Careers", ar: "الوظائف" },
  "menu.newsroom": { en: "Newsroom", ar: "غرفة الأخبار" },
  "menu.contactGeneral": { en: "Contact Us", ar: "تواصل معنا" },
  "menu.ammanOffice": { en: "Amman Office", ar: "مكتب عمّان" },
  
  "menu.baghdadOffice": { en: "Baghdad Office", ar: "مكتب بغداد" },
  "menu.generalInquiries": { en: "General Inquiries", ar: "استفسارات عامة" },

  // New MegaMenu keys
  "mega.ourCompanies": { en: "Our Companies", ar: "شركاتنا" },
  "mega.ourSpecializations": { en: "Our Specializations", ar: "تخصصاتنا" },
  "mega.ourProjects": { en: "Our Projects", ar: "مشاريعنا" },
  "mega.contactUs": { en: "Contact Us", ar: "تواصل معنا" },
  "mega.oilGas": { en: "Oil & Gas", ar: "النفط والغاز" },
  "mega.medical": { en: "Medical", ar: "الطبية" },
  "mega.robotics": { en: "Robotics", ar: "الروبوتات" },
  "mega.energy": { en: "Energy", ar: "الطاقة" },
  "mega.pipesSupply": { en: "Oil & Gas Pipes Supply", ar: "توريد أنابيب النفط والغاز" },
  "mega.drillingEquipment": { en: "Drilling Equipment", ar: "معدات الحفر" },
  "mega.explorationReq": { en: "Exploration Requirements", ar: "متطلبات الاستكشاف" },
  "mega.tcInspection": { en: "T.C Equipment & Inspection", ar: "معدات الفحص والتحكم التقني" },
  "mega.underground": { en: "Underground Infrastructure", ar: "البنية التحتية تحت الأرض" },
  "mega.ogAfterSales": { en: "After-Sales Support", ar: "دعم ما بعد البيع" },
  "mega.biomedical": { en: "Biomedical Engineering", ar: "الهندسة الطبية الحيوية" },
  "mega.hospitalEquip": { en: "Hospital Equipment Supply", ar: "توريد معدات المستشفيات" },
  "mega.capacityMgmt": { en: "Capacity Management", ar: "إدارة السعة" },
  "mega.turnkey": { en: "Turnkey Medical Projects", ar: "مشاريع طبية متكاملة" },
  "mega.tenderMgmt": { en: "Medical Tender Management", ar: "إدارة المناقصات الطبية" },
  "mega.medAfterSales": { en: "After-Sales Support", ar: "دعم ما بعد البيع" },
  "mega.roboticsSchools": { en: "Robotics for Schools", ar: "الروبوتات للمدارس" },
  "mega.aiProgramming": { en: "AI & Programming", ar: "الذكاء الاصطناعي والبرمجة" },
  "mega.roboticsEquip": { en: "Robotics Equipment Supply", ar: "توريد معدات الروبوتات" },
  "mega.corpTraining": { en: "Corporate Training", ar: "تدريب الشركات" },
  "mega.comingSoon": { en: "Coming Soon", ar: "قريباً" },
  "mega.cleanEnergy": { en: "Clean Energy Manufacturing", ar: "تصنيع الطاقة النظيفة" },
  "mega.contactGeneral": { en: "Contact Us (General)", ar: "تواصل معنا (عام)" },
  "mega.ammanOffice": { en: "Amman Office", ar: "مكتب عمّان" },
  
  "mega.email": { en: "Email", ar: "البريد الإلكتروني" },
  "mega.jordan": { en: "Jordan", ar: "الأردن" },
  "mega.iraq": { en: "Iraq", ar: "العراق" },
  "mega.careers": { en: "Careers", ar: "الوظائف" },

  // Contact page
  "contact.heroLabel": { en: "We'd Love To Hear From You", ar: "يسعدنا سماعك" },
  "contact.heroHeading": { en: "Get In Touch", ar: "تواصل معنا" },
  "contact.offices": { en: "Our Offices", ar: "مكاتبنا" },
  "contact.amman": { en: "Amman, Jordan", ar: "عمّان، الأردن" },
  "contact.hq": { en: "Headquarters", ar: "المقر الرئيسي" },
  
  "contact.baghdad": { en: "Baghdad, Iraq", ar: "بغداد، العراق" },
  "contact.branch": { en: "Branch Office", ar: "مكتب فرعي" },
  "contact.email": { en: "Email", ar: "البريد الإلكتروني" },
  "contact.followUs": { en: "Follow Us", ar: "تابعنا" },
  "contact.whichOffice": { en: "Which office would you like to contact?", ar: "أي مكتب تود التواصل معه؟" },
  "contact.selectOffice": { en: "Select an office", ar: "اختر مكتباً" },
  "contact.officeAmman": { en: "Amman, Jordan", ar: "عمّان، الأردن" },
  
  "contact.fullName": { en: "Full Name", ar: "الاسم الكامل" },
  "contact.fullNamePlaceholder": { en: "Your full name", ar: "اسمك الكامل" },
  "contact.emailAddress": { en: "Email Address", ar: "البريد الإلكتروني" },
  "contact.emailPlaceholder": { en: "you@example.com", ar: "you@example.com" },
  "contact.phone": { en: "Phone Number", ar: "رقم الهاتف" },
  "contact.phonePlaceholder": { en: "+962 7XX XXX XXX", ar: "+٩٦٢ ٧XX XXX XXX" },
  "contact.subject": { en: "Subject", ar: "الموضوع" },
  "contact.subjectPlaceholder": { en: "Select a subject", ar: "اختر موضوعاً" },
  "contact.message": { en: "Message", ar: "الرسالة" },
  "contact.messagePlaceholder": { en: "Tell us about your project or inquiry...", ar: "أخبرنا عن مشروعك أو استفسارك..." },
  "contact.send": { en: "Send Message", ar: "إرسال الرسالة" },
  "contact.subjectOilGas": { en: "Oil & Gas", ar: "النفط والغاز" },
  "contact.subjectMedical": { en: "Medical", ar: "الطبية" },
  "contact.subjectRobotics": { en: "Robotics", ar: "الروبوتات" },
  "contact.subjectEnergy": { en: "Energy", ar: "الطاقة" },
  "contact.subjectEngConsultancy": { en: "Engineering Consultancy", ar: "الاستشارات الهندسية" },
  "contact.subjectEduTech": { en: "Educational Technology", ar: "التكنولوجيا التعليمية" },
  "contact.subjectEquipSupply": { en: "Equipment Supply", ar: "توريد المعدات" },
  "contact.subjectGeneral": { en: "General Inquiry", ar: "استفسار عام" },

  // Engineering Consultancy page
  "eng.heroLabel": { en: "Engineering Consultancy Division", ar: "قسم الاستشارات الهندسية" },
  "eng.heroH1": { en: "Built to Last.", ar: "بُنيت لتدوم." },
  "eng.heroH2": { en: "Engineered to Excel.", ar: "صُممت للتميز." },
  "eng.whatWeDo": { en: "What We Do", ar: "ما نقوم به" },
  "eng.heading": { en: "Comprehensive Engineering Solutions", ar: "حلول هندسية شاملة" },
  "eng.text": { en: "AL-JADRIYA Engineering Consultancy Division delivers end-to-end technical solutions across multiple sectors. From initial feasibility studies to full project execution, our qualified team of engineers ensures every project meets the highest standards of quality and safety.", ar: "يقدم قسم الاستشارات الهندسية في الجادرية حلولاً تقنية متكاملة عبر قطاعات متعددة. من دراسات الجدوى الأولية إلى التنفيذ الكامل للمشاريع، يضمن فريقنا المؤهل من المهندسين أن كل مشروع يلبي أعلى معايير الجودة والسلامة." },
  "eng.whatWeOffer": { en: "What We Offer", ar: "ما نقدمه" },
  "eng.ourServices": { en: "Our Services", ar: "خدماتنا" },
  "eng.feasibility": { en: "Feasibility Studies", ar: "دراسات الجدوى" },
  "eng.feasibilityDesc": { en: "In-depth technical and financial analysis before project launch.", ar: "تحليل تقني ومالي معمق قبل إطلاق المشروع." },
  "eng.projectDesign": { en: "Project Design", ar: "تصميم المشاريع" },
  "eng.projectDesignDesc": { en: "Complete architectural and engineering design solutions.", ar: "حلول تصميم معماري وهندسي متكاملة." },
  "eng.procurement": { en: "Procurement", ar: "المشتريات" },
  "eng.procurementDesc": { en: "Strategic sourcing of equipment and materials from trusted suppliers.", ar: "توريد استراتيجي للمعدات والمواد من موردين موثوقين." },
  "eng.pipeline": { en: "Pipeline Engineering", ar: "هندسة خطوط الأنابيب" },
  "eng.pipelineDesc": { en: "Design and execution of industrial pipeline systems.", ar: "تصميم وتنفيذ أنظمة خطوط الأنابيب الصناعية." },
  "eng.medical": { en: "Medical Facility Engineering", ar: "هندسة المرافق الطبية" },
  "eng.medicalDesc": { en: "Specialized consultancy for hospitals and healthcare infrastructure.", ar: "استشارات متخصصة للمستشفيات والبنية التحتية الصحية." },
  "eng.turnkey": { en: "Turnkey Projects", ar: "مشاريع متكاملة" },
  "eng.turnkeyDesc": { en: "Full project management from concept to handover.", ar: "إدارة كاملة للمشاريع من المفهوم إلى التسليم." },
  "eng.whyChoose": { en: "Why Choose Us", ar: "لماذا تختارنا" },
  "eng.provenTrack": { en: "Proven Track Record", ar: "سجل حافل بالإنجازات" },
  "eng.countries": { en: "Countries", ar: "الدول" },
  "eng.markets": { en: "Markets", ar: "الأسواق" },
  "eng.yearsExp": { en: "Years Experience", ar: "سنوات الخبرة" },
  "eng.projectsDelivered": { en: "Projects Delivered", ar: "مشاريع منجزة" },
  "eng.visionHeading": { en: "Your Project, Our Commitment", ar: "مشروعك، التزامنا" },
  "eng.visionText": { en: "We combine deep regional knowledge with international engineering standards to deliver projects that stand the test of time. Every client, every project, every sector, we bring the same level of dedication and precision.", ar: "نجمع بين المعرفة الإقليمية العميقة والمعايير الهندسية الدولية لتقديم مشاريع تصمد أمام اختبار الزمن. كل عميل، كل مشروع، كل قطاع، نقدم نفس المستوى من التفاني والدقة." },
  "eng.contactUs": { en: "Contact Us", ar: "تواصل معنا" },

  // Educational Technology page
  "edu.heroLabel": { en: "Educational Technology Division", ar: "قسم التكنولوجيا التعليمية" },
  "edu.heroH1": { en: "Shaping the", ar: "نصنع" },
  "edu.heroH2": { en: "Next Generation.", ar: "الجيل القادم." },
  "edu.whoWeServe": { en: "Who We Serve", ar: "من نخدم" },
  "edu.heading": { en: "World-Class Training for the AI Era", ar: "تدريب عالمي المستوى لعصر الذكاء الاصطناعي" },
  "edu.text": { en: "AL-JADRIYA Educational Technology Division equips schools, professionals, and career-shifters with the skills demanded by tomorrow's economy. Through robotics, programming, and AI programs delivered in-person and online, we build the workforce of the future.", ar: "يزود قسم التكنولوجيا التعليمية في الجادرية المدارس والمهنيين والمتحولين مهنياً بالمهارات التي يتطلبها اقتصاد الغد. من خلال برامج الروبوتات والبرمجة والذكاء الاصطناعي المقدمة حضورياً وعبر الإنترنت، نبني قوة عمل المستقبل." },
  "edu.whatWeOffer": { en: "What We Offer", ar: "ما نقدمه" },
  "edu.ourPrograms": { en: "Our Programs", ar: "برامجنا" },
  "edu.roboticsSchools": { en: "Robotics for Schools", ar: "الروبوتات للمدارس" },
  "edu.roboticsSchoolsDesc": { en: "Curriculum-aligned robotics programs delivered directly to schools.", ar: "برامج روبوتات متوافقة مع المناهج تُقدم مباشرة للمدارس." },
  "edu.aiProgramming": { en: "AI & Programming", ar: "الذكاء الاصطناعي والبرمجة" },
  "edu.aiProgrammingDesc": { en: "Hands-on coding and artificial intelligence courses for all levels.", ar: "دورات عملية في البرمجة والذكاء الاصطناعي لجميع المستويات." },
  "edu.upskilling": { en: "Professional Upskilling", ar: "تطوير المهارات المهنية" },
  "edu.upskillingDesc": { en: "Advanced training for IT professionals entering the AI economy.", ar: "تدريب متقدم لمحترفي تكنولوجيا المعلومات الداخلين لاقتصاد الذكاء الاصطناعي." },
  "edu.womenInTech": { en: "Women in Tech", ar: "المرأة في التكنولوجيا" },
  "edu.womenInTechDesc": { en: "Dedicated programs supporting women entering or transitioning into technology careers.", ar: "برامج مخصصة لدعم النساء الداخلات أو المنتقلات إلى المهن التقنية." },
  "edu.corporateTraining": { en: "Corporate Training", ar: "تدريب الشركات" },
  "edu.corporateTrainingDesc": { en: "Custom training solutions designed for institutions and organizations at scale.", ar: "حلول تدريب مخصصة مصممة للمؤسسات والمنظمات على نطاق واسع." },
  "edu.onlineLearning": { en: "Online Learning", ar: "التعلم عبر الإنترنت" },
  "edu.onlineLearningDesc": { en: "Flexible online programs accessible from anywhere in the region.", ar: "برامج مرنة عبر الإنترنت يمكن الوصول إليها من أي مكان في المنطقة." },
  "edu.ourImpact": { en: "Our Impact", ar: "أثرنا" },
  "edu.makingDifference": { en: "Making a Difference", ar: "نصنع الفارق" },
  "edu.countries": { en: "Countries", ar: "الدول" },
  "edu.markets": { en: "Markets", ar: "الأسواق" },
  "edu.graduates": { en: "Graduates", ar: "الخريجون" },
  "edu.schoolPartners": { en: "School Partners", ar: "شركاء المدارس" },
  "edu.trainingCenter": { en: "A Fully Equipped Training Center", ar: "مركز تدريب مجهز بالكامل" },
  "edu.trainingText": { en: "Our training center in Amman features prepared classrooms, certified trainers, and complete technical infrastructure. We deliver programs both in-person and online, serving schools, professionals, and institutions across the region.", ar: "يتميز مركزنا التدريبي في عمّان بفصول دراسية مجهزة ومدربين معتمدين وبنية تحتية تقنية متكاملة. نقدم البرامج حضورياً وعبر الإنترنت، لخدمة المدارس والمهنيين والمؤسسات في جميع أنحاء المنطقة." },
  "edu.contactUs": { en: "Contact Us", ar: "تواصل معنا" },
  "edu.whoCanJoin": { en: "Who Can Join", ar: "من يمكنه الانضمام" },
  "edu.whoIsThisFor": { en: "Who Is This For?", ar: "لمن هذا؟" },
  "edu.schools": { en: "Schools", ar: "المدارس" },
  "edu.schoolsDesc": { en: "Curriculum-aligned robotics and AI programs for students of all ages.", ar: "برامج روبوتات وذكاء اصطناعي متوافقة مع المناهج لطلاب جميع الأعمار." },
  "edu.itProfessionals": { en: "IT Professionals", ar: "محترفو تكنولوجيا المعلومات" },
  "edu.itProfessionalsDesc": { en: "Advance your career into artificial intelligence and automation.", ar: "طوّر مسيرتك المهنية نحو الذكاء الاصطناعي والأتمتة." },
  "edu.womenInTechAudience": { en: "Women in Tech", ar: "المرأة في التكنولوجيا" },
  "edu.womenInTechAudienceDesc": { en: "Start or transition your career into the technology sector.", ar: "ابدئي أو انتقلي بمسيرتك المهنية إلى قطاع التكنولوجيا." },
  "edu.institutions": { en: "Institutions", ar: "المؤسسات" },
  "edu.institutionsDesc": { en: "Large-scale training solutions for organizations and government bodies.", ar: "حلول تدريب واسعة النطاق للمنظمات والهيئات الحكومية." },

  // Equipment Supply page
  "equip.heroLabel": { en: "Equipment Supply & Tenders", ar: "توريد المعدات والمناقصات" },
  "equip.heroH1": { en: "The Right Equipment.", ar: "المعدات المناسبة." },
  "equip.heroH2": { en: "Delivered on Time.", ar: "تُسلّم في الوقت المحدد." },
  "equip.whatWeDo": { en: "What We Do", ar: "ما نقوم به" },
  "equip.heading": { en: "End-to-End Equipment Supply Solutions", ar: "حلول توريد معدات متكاملة" },
  "equip.text": { en: "AL-JADRIYA Engineering provides comprehensive equipment supply services for engineering, industrial, medical, and educational technology projects. We manage the full procurement cycle, from sourcing and tendering to delivery and after-sales support, ensuring our clients receive the right equipment at the right time.", ar: "توفر الجادرية للهندسة خدمات شاملة لتوريد المعدات لمشاريع الهندسة والصناعة والطب والتكنولوجيا التعليمية. ندير دورة الشراء الكاملة، من التوريد والمناقصات إلى التسليم ودعم ما بعد البيع." },
  "equip.whatWeOffer": { en: "What We Offer", ar: "ما نقدمه" },
  "equip.whatWeSupply": { en: "What We Supply", ar: "ما نورّده" },
  "equip.industrial": { en: "Industrial Equipment", ar: "معدات صناعية" },
  "equip.industrialDesc": { en: "Heavy machinery and industrial tools for infrastructure and pipeline projects.", ar: "آلات ثقيلة وأدوات صناعية لمشاريع البنية التحتية وخطوط الأنابيب." },
  "equip.medical": { en: "Medical Equipment", ar: "معدات طبية" },
  "equip.medicalDesc": { en: "Specialized medical devices and hospital infrastructure equipment.", ar: "أجهزة طبية متخصصة ومعدات البنية التحتية للمستشفيات." },
  "equip.eduTech": { en: "Educational Technology", ar: "تكنولوجيا تعليمية" },
  "equip.eduTechDesc": { en: "Robotics kits, coding hardware, and AI learning tools for schools and training centers.", ar: "مجموعات الروبوتات وأجهزة البرمجة وأدوات تعلم الذكاء الاصطناعي للمدارس ومراكز التدريب." },
  "equip.construction": { en: "Construction Materials", ar: "مواد البناء" },
  "equip.constructionDesc": { en: "High-quality materials sourced from trusted international suppliers.", ar: "مواد عالية الجودة من موردين دوليين موثوقين." },
  "equip.tenders": { en: "Tender Management", ar: "إدارة المناقصات" },
  "equip.tendersDesc": { en: "Full capability to prepare, submit, and manage government and private sector tenders.", ar: "قدرة كاملة على إعداد وتقديم وإدارة مناقصات القطاعين العام والخاص." },
  "equip.afterSales": { en: "After-Sales Support", ar: "دعم ما بعد البيع" },
  "equip.afterSalesDesc": { en: "Installation, maintenance, and technical support for all supplied equipment.", ar: "التركيب والصيانة والدعم الفني لجميع المعدات الموردة." },
  "equip.ourReach": { en: "Our Reach", ar: "نطاق وصولنا" },
  "equip.globalSupply": { en: "Global Supply Network", ar: "شبكة توريد عالمية" },
  "equip.markets": { en: "Markets", ar: "الأسواق" },
  "equip.countries": { en: "Countries", ar: "الدول" },
  "equip.suppliers": { en: "Suppliers", ar: "الموردون" },
  "equip.tendersWon": { en: "Tenders Won", ar: "مناقصات فائزة" },
  "equip.promiseHeading": { en: "Quality You Can Trust", ar: "جودة يمكنك الوثوق بها" },
  "equip.promiseText": { en: "Every piece of equipment we supply meets strict quality and safety standards. We work exclusively with certified international partners and manufacturers to ensure our clients receive only the best — backed by full after-sales support and technical expertise.", ar: "كل قطعة معدات نوردها تلبي معايير صارمة للجودة والسلامة. نعمل حصرياً مع شركاء ومصنعين دوليين معتمدين لضمان حصول عملائنا على الأفضل فقط - مدعومة بدعم كامل بعد البيع وخبرة تقنية." },
  "equip.contactUs": { en: "Contact Us", ar: "تواصل معنا" },
  "equip.marketsWeServe": { en: "Markets We Serve", ar: "الأسواق التي نخدمها" },
  "equip.whereWeOperate": { en: "Where We Operate", ar: "أين نعمل" },

  // Company Cards Section
  "cards.sectionLabel": { en: "OUR COMPANIES", ar: "شركاتنا" },
  "cards.oilgas.label": { en: "Oil & Gas", ar: "النفط والغاز" },
  "cards.oilgas.headline": { en: "Supply. Deliver.", ar: "نورّد. نسلّم." },
  "cards.medical.label": { en: "Medical", ar: "الطبية" },
  "cards.medical.headline": { en: "From Equipment to Full Hospitals.", ar: "من المعدات إلى مستشفيات كاملة." },
  "cards.robotics.label": { en: "Robotics", ar: "الروبوتات" },
  "cards.robotics.headline": { en: "Tomorrow's Engineers, Today.", ar: "مهندسو الغد، اليوم." },
  "cards.energy.label": { en: "Energy", ar: "الطاقة" },
  "cards.energy.headline": { en: "Coming Soon.", ar: "قريباً." },

  // Who We Serve Section
  "serve.label": { en: "WHO WE SERVE", ar: "من نخدم" },
  "serve.heading": { en: "Leading in engineering, education, and innovation", ar: "رائدون في الهندسة والتعليم والابتكار" },
  "serve.text": { en: "We are an integrated engineering and educational technology company, serving Jordan, Iraq, and the wider region. From complex engineering consultancy to world-class AI and robotics training programs, we build the future on two fronts.", ar: "نحن شركة هندسية وتكنولوجيا تعليمية متكاملة، نخدم الأردن والعراق والمنطقة الأوسع. من الاستشارات الهندسية المعقدة إلى برامج تدريب الذكاء الاصطناعي والروبوتات على مستوى عالمي، نبني المستقبل على جبهتين." },
  "serve.cta": { en: "Explore Our Companies →", ar: "استكشف شركاتنا ←" },
  "serve.jordan": { en: "Jordan", ar: "الأردن" },
  "serve.iraq": { en: "Iraq", ar: "العراق" },
  "serve.uae": { en: "UAE", ar: "الإمارات" },
  "serve.saudi": { en: "Saudi Arabia", ar: "السعودية" },
  "serve.egypt": { en: "Egypt", ar: "مصر" },
  "serve.libya": { en: "Libya", ar: "ليبيا" },

  // Specializations Section
  "spec.label": { en: "OUR SPECIALIZATIONS", ar: "تخصصاتنا" },
  "spec.tab.oilgas": { en: "Oil & Gas", ar: "النفط والغاز" },
  "spec.tab.medical": { en: "Medical", ar: "الطبية" },
  "spec.tab.robotics": { en: "Robotics", ar: "الروبوتات" },
  "spec.tab.energy": { en: "Energy", ar: "الطاقة" },
  "spec.oilgas.1": { en: "Oil & Gas Pipes Supply", ar: "توريد أنابيب النفط والغاز" },
  "spec.oilgas.1.desc": { en: "Supply of high-grade steel pipes and fittings for oil and gas infrastructure across the region.", ar: "توريد أنابيب ومواسير فولاذية عالية الجودة للبنية التحتية للنفط والغاز في المنطقة." },
  "spec.oilgas.2": { en: "Drilling Equipment", ar: "معدات الحفر" },
  "spec.oilgas.2.desc": { en: "Complete drilling equipment solutions for exploration and extraction operations in demanding environments.", ar: "حلول معدات حفر متكاملة لعمليات الاستكشاف والاستخراج في البيئات الصعبة." },
  "spec.oilgas.3": { en: "Exploration Requirements", ar: "متطلبات الاستكشاف" },
  "spec.oilgas.3.desc": { en: "Specialized tools and technical support for geological surveys and field exploration projects.", ar: "أدوات متخصصة ودعم فني للمسوحات الجيولوجية ومشاريع الاستكشاف الميداني." },
  "spec.oilgas.4": { en: "T.C Equipment & Inspection", ar: "معدات وتفتيش T.C" },
  "spec.oilgas.4.desc": { en: "Technical control equipment supply with full inspection and acceptance services on-site.", ar: "توريد معدات الرقابة الفنية مع خدمات التفتيش والقبول الكاملة في الموقع." },
  "spec.oilgas.5": { en: "Underground Infrastructure", ar: "البنية التحتية تحت الأرض" },
  "spec.oilgas.5.desc": { en: "Design and supply of underground pipeline systems built for long-term industrial performance.", ar: "تصميم وتوريد أنظمة الأنابيب تحت الأرض المصممة للأداء الصناعي طويل الأمد." },
  "spec.medical.1": { en: "Biomedical Engineering", ar: "الهندسة الطبية الحيوية" },
  "spec.medical.1.desc": { en: "Engineering consultancy and technical support for biomedical systems across healthcare facilities.", ar: "استشارات هندسية ودعم فني لأنظمة الهندسة الطبية الحيوية في المرافق الصحية." },
  "spec.medical.2": { en: "Hospital Equipment Supply", ar: "توريد معدات المستشفيات" },
  "spec.medical.2.desc": { en: "Full supply of medical devices and hospital equipment sourced from leading international manufacturers.", ar: "توريد كامل للأجهزة الطبية ومعدات المستشفيات من كبار المصنعين الدوليين." },
  "spec.medical.3": { en: "Capacity Management", ar: "إدارة القدرات" },
  "spec.medical.3.desc": { en: "Strategic planning solutions to optimize hospital capacity, patient flow, and operational efficiency.", ar: "حلول تخطيط استراتيجي لتحسين سعة المستشفيات وتدفق المرضى والكفاءة التشغيلية." },
  "spec.medical.4": { en: "Turnkey Medical Projects", ar: "مشاريع طبية متكاملة" },
  "spec.medical.4.desc": { en: "End-to-end delivery of fully equipped medical facilities, from planning to final handover.", ar: "تسليم شامل لمرافق طبية مجهزة بالكامل، من التخطيط إلى التسليم النهائي." },
  "spec.medical.5": { en: "Medical Tender Management", ar: "إدارة المناقصات الطبية" },
  "spec.medical.5.desc": { en: "Expert management of medical procurement tenders for hospitals and healthcare institutions.", ar: "إدارة احترافية لمناقصات المشتريات الطبية للمستشفيات والمؤسسات الصحية." },
  "spec.robotics.1": { en: "Robotics for Schools", ar: "الروبوتات للمدارس" },
  "spec.robotics.1.desc": { en: "Curriculum-aligned robotics programs delivered directly to schools, building skills for the AI era.", ar: "برامج روبوتات متوافقة مع المناهج تُقدم مباشرة للمدارس لبناء مهارات عصر الذكاء الاصطناعي." },
  "spec.robotics.2": { en: "AI & Programming", ar: "الذكاء الاصطناعي والبرمجة" },
  "spec.robotics.2.desc": { en: "Hands-on coding and artificial intelligence courses for students and professionals at all levels.", ar: "دورات عملية في البرمجة والذكاء الاصطناعي للطلاب والمحترفين بجميع المستويات." },
  "spec.robotics.3": { en: "Robotics Equipment Supply", ar: "توريد معدات الروبوتات" },
  "spec.robotics.3.desc": { en: "Supply of professional robotics kits and equipment for educational and corporate training purposes.", ar: "توريد أطقم ومعدات روبوتات احترافية لأغراض التدريب التعليمي والمؤسسي." },
  "spec.robotics.4": { en: "Corporate Training", ar: "تدريب الشركات" },
  "spec.robotics.4.desc": { en: "Custom robotics and AI training programs designed for organizations and institutions at scale.", ar: "برامج تدريب مخصصة في الروبوتات والذكاء الاصطناعي مصممة للمؤسسات على نطاق واسع." },
  "spec.energy.1": { en: "Clean Energy Manufacturing", ar: "تصنيع الطاقة النظيفة" },
  "spec.energy.1.desc": { en: "Supporting the design and supply chain for clean energy manufacturing facilities across the region.", ar: "دعم التصميم وسلسلة التوريد لمرافق تصنيع الطاقة النظيفة في المنطقة." },
  "spec.energy.2": { en: "Wind Energy", ar: "طاقة الرياح" },
  "spec.energy.2.desc": { en: "Consultancy and equipment solutions for wind energy projects and infrastructure development.", ar: "استشارات وحلول معدات لمشاريع طاقة الرياح وتطوير البنية التحتية." },
  "spec.energy.3": { en: "Solar Solutions", ar: "حلول الطاقة الشمسية" },
  "spec.energy.3.desc": { en: "Supply and technical support for solar panel systems and photovoltaic installations.", ar: "توريد ودعم فني لأنظمة الألواح الشمسية والتركيبات الكهروضوئية." },

  // Footer (new keys)
  "footer.brand": { en: "AL-JADRIYA GROUP", ar: "مجموعة الجادرية" },
  "footer.tagline": { en: "Advanced Engineering Technology Group", ar: "مجموعة التكنولوجيا الهندسية المتقدمة" },
  "footer.companies": { en: "Our Companies", ar: "شركاتنا" },
  "footer.oilgas": { en: "Oil & Gas", ar: "النفط والغاز" },
  "footer.medical": { en: "Medical", ar: "الطبية" },
  "footer.robotics": { en: "Robotics", ar: "الروبوتات" },
  "footer.energy": { en: "Energy", ar: "الطاقة" },
  "footer.quickLinks": { en: "Quick Links", ar: "روابط سريعة" },
  "footer.careers": { en: "Careers", ar: "الوظائف" },
  "footer.ammanAddress": { en: "Wasfi Al-Tal St, Building 124", ar: "شارع وصفي التل، بناية ١٢٤" },
  "footer.rights": { en: "© 2026 AL-JADRIYA GROUP. All rights reserved.", ar: "© ٢٠٢٦ مجموعة الجادرية. جميع الحقوق محفوظة." },
  "footer.comingSoon": { en: "Coming Soon", ar: "قريباً" },
  "footer.ammanOffice": { en: "Amman Office", ar: "مكتب عمّان" },
  

  // Contact Form
  "form.contactInfo": { en: "Contact Information", ar: "معلومات الاتصال" },
  "form.firstName": { en: "First Name", ar: "الاسم الأول" },
  "form.lastName": { en: "Last Name", ar: "اسم العائلة" },
  "form.email": { en: "E-mail", ar: "البريد الإلكتروني" },
  "form.companyOrg": { en: "Company / Organization", ar: "الشركة / المؤسسة" },
  "form.country": { en: "Country", ar: "الدولة" },
  "form.selectCountry": { en: "Select country", ar: "اختر الدولة" },
  "form.phone": { en: "Phone", ar: "الهاتف" },
  "form.phoneHint": { en: "Start with international dialing code. Eg. 962 788310769", ar: "ابدأ برمز الاتصال الدولي. مثال: ٩٦٢ ٧٨٨٣١٠٧٦٩" },
  "form.message": { en: "Message", ar: "الرسالة" },
  "form.whichOffice": { en: "Which office?", ar: "أي مكتب؟" },
  "form.selectOffice": { en: "Select office", ar: "اختر مكتباً" },
  "form.ammanJordan": { en: "Amman, Jordan", ar: "عمّان، الأردن" },
  
  "form.whichCompany": { en: "Which company?", ar: "أي شركة؟" },
  "form.selectCompany": { en: "Select company", ar: "اختر شركة" },
  "form.oilGas": { en: "Oil & Gas", ar: "النفط والغاز" },
  "form.medical": { en: "Medical", ar: "الطبية" },
  "form.robotics": { en: "Robotics", ar: "الروبوتات" },
  "form.energy": { en: "Energy", ar: "الطاقة" },
  "form.general": { en: "General", ar: "عام" },
  "form.inquiryType": { en: "Type of inquiry", ar: "نوع الاستفسار" },
  "form.selectType": { en: "Select type", ar: "اختر النوع" },
  "form.requestQuote": { en: "Request a Quote", ar: "طلب عرض سعر" },
  "form.techSupport": { en: "Technical Support", ar: "دعم فني" },
  "form.partnership": { en: "Partnership", ar: "شراكة" },
  "form.generalInquiry": { en: "General Inquiry", ar: "استفسار عام" },
  "form.privacy": { en: "Your information is kept private and will only be used to respond to your inquiry.", ar: "معلوماتك محفوظة بسرية ولن تُستخدم إلا للرد على استفسارك." },
  "form.send": { en: "Send Message", ar: "إرسال الرسالة" },
  "form.thankYou": { en: "Thank you.", ar: "شكراً لك." },
  "form.thankYouMsg": { en: "We will get back to you shortly.", ar: "سنعود إليك قريباً." },
  "form.jordan": { en: "Jordan", ar: "الأردن" },
  "form.iraq": { en: "Iraq", ar: "العراق" },
  "form.saudiArabia": { en: "Saudi Arabia", ar: "السعودية" },
  "form.uae": { en: "UAE", ar: "الإمارات" },
  "form.kuwait": { en: "Kuwait", ar: "الكويت" },
  "form.qatar": { en: "Qatar", ar: "قطر" },
  "form.bahrain": { en: "Bahrain", ar: "البحرين" },
  "form.oman": { en: "Oman", ar: "عُمان" },
  "form.egypt": { en: "Egypt", ar: "مصر" },
  "form.other": { en: "Other", ar: "أخرى" },

  // Oil & Gas Company
  "og.oilAndGas": { en: "Oil & Gas", ar: "النفط والغاز" },
  "og.backToGroup": { en: "← AL-JADRIYA GROUP", ar: "مجموعة الجادرية →" },
  "og.backToGroupShort": { en: "AL-JADRIYA GROUP", ar: "مجموعة الجادرية" },
  "og.brandFull": { en: "AL-JADRIYA OIL & GAS", ar: "الجادرية للنفط والغاز" },
  "og.footerTagline": { en: "Specialized supplier of oil and gas equipment across the region.", ar: "مورّد متخصص لمعدات النفط والغاز في المنطقة." },
  "og.rights": { en: "© 2026 AL-JADRIYA OIL & GAS. All rights reserved.", ar: "© ٢٠٢٦ الجادرية للنفط والغاز. جميع الحقوق محفوظة." },
  "og.services": { en: "Our Services", ar: "خدماتنا" },

  // Hero slides
  "og.hero1.label": { en: "OIL & GAS PIPES SUPPLY", ar: "توريد أنابيب النفط والغاز" },
  "og.hero1.heading": { en: "The Right Pipe. Every Specification. On Time.", ar: "الأنبوب المناسب. كل المواصفات. في الوقت المحدد." },
  "og.hero1.tab": { en: "Pipes", ar: "الأنابيب" },
  "og.hero2.label": { en: "DRILLING EQUIPMENT", ar: "معدات الحفر" },
  "og.hero2.heading": { en: "Every Tool Your Drill Site Demands.", ar: "كل أداة يحتاجها موقع الحفر." },
  "og.hero2.tab": { en: "Drilling", ar: "الحفر" },
  "og.hero3.label": { en: "EXPLORATION REQUIREMENTS", ar: "متطلبات الاستكشاف" },
  "og.hero3.heading": { en: "Supplying the Instruments That Find What's Below.", ar: "نورّد الأدوات التي تكتشف ما تحت الأرض." },
  "og.hero3.tab": { en: "Exploration", ar: "الاستكشاف" },
  "og.hero4.label": { en: "T.C EQUIPMENT & INSPECTION", ar: "معدات وتفتيش الرقابة الفنية" },
  "og.hero4.heading": { en: "Precision Instruments for Every Quality Check.", ar: "أدوات دقيقة لكل فحص جودة." },
  "og.hero4.tab": { en: "Inspection", ar: "التفتيش" },
  "og.hero5.label": { en: "UNDERGROUND INFRASTRUCTURE", ar: "البنية التحتية تحت الأرض" },
  "og.hero5.heading": { en: "Materials Built for What Lies Beneath.", ar: "مواد مصنّعة لما يكمن في الأعماق." },
  "og.hero5.tab": { en: "Underground", ar: "تحت الأرض" },
  "og.hero6.label": { en: "AFTER-SALES SUPPORT", ar: "دعم ما بعد البيع" },
  "og.hero6.heading": { en: "With You After Every Delivery.", ar: "معكم بعد كل تسليم." },
  "og.hero6.tab": { en: "Support", ar: "الدعم" },

  // Services section
  "og.whatWeOfferLabel": { en: "WHAT WE OFFER", ar: "ما نقدمه" },
  "og.whatWeOffer": { en: "What We Offer", ar: "ما نقدمه" },
  "og.servicesHeading": { en: "Six Specialized Supply Lines. One Trusted Partner.", ar: "ستة خطوط توريد متخصصة. شريك واحد موثوق." },
  "og.pipesSupply": { en: "Oil & Gas Pipes Supply", ar: "توريد أنابيب النفط والغاز" },
  "og.pipesDesc": { en: "AL-JADRIYA Oil & Gas supplies high-grade steel pipes, fittings, and pipeline materials from certified international manufacturers. We source and deliver the right pipe specifications for your project — on time and to standard.", ar: "توفر الجادرية للنفط والغاز أنابيب فولاذية عالية الجودة ووصلات ومواد خطوط الأنابيب من مصنعين دوليين معتمدين. نوفر ونسلّم المواصفات المناسبة لمشروعك — في الوقت المحدد وبالمعايير المطلوبة." },
  "og.drillingEquipment": { en: "Drilling Equipment", ar: "معدات الحفر" },
  "og.drillingDesc": { en: "We supply a comprehensive range of drilling equipment and tools to oil and gas operators and contractors across the region. From drill bits and casings to downhole tools and accessories — we source and deliver what your drilling operation requires.", ar: "نورّد مجموعة شاملة من معدات وأدوات الحفر لمشغلي ومقاولي النفط والغاز في المنطقة. من رؤوس الحفر والأغلفة إلى أدوات أسفل البئر والملحقات — نوفر ونسلّم ما تحتاجه عملية الحفر." },
  "og.exploration": { en: "Exploration Requirements", ar: "متطلبات الاستكشاف" },
  "og.explorationDesc": { en: "AL-JADRIYA supplies specialized instruments and equipment for geological surveys, seismic operations, and field exploration programs. We provide the tools — your teams do the work.", ar: "توفر الجادرية أدوات ومعدات متخصصة للمسوحات الجيولوجية والعمليات الزلزالية وبرامج الاستكشاف الميداني. نوفر الأدوات — وفرقكم تنجز العمل." },
  "og.inspection": { en: "T.C Equipment & Inspection", ar: "معدات وتفتيش الرقابة الفنية" },
  "og.inspectionDesc": { en: "We supply technical control and inspection instruments used for pipeline quality verification, weld inspection, and field testing. All equipment is sourced from certified manufacturers and delivered with full documentation.", ar: "نورّد أجهزة الرقابة الفنية والتفتيش المستخدمة للتحقق من جودة خطوط الأنابيب وفحص اللحام والاختبارات الميدانية. جميع المعدات من مصنعين معتمدين وتُسلّم بتوثيق كامل." },
  "og.underground": { en: "Underground Infrastructure", ar: "البنية التحتية تحت الأرض" },
  "og.undergroundDesc": { en: "AL-JADRIYA supplies pipes, fittings, and materials used in underground pipeline and infrastructure projects for industrial and municipal applications. We deliver the right materials to your project site.", ar: "توفر الجادرية الأنابيب والوصلات والمواد المستخدمة في مشاريع خطوط الأنابيب والبنية التحتية تحت الأرض للتطبيقات الصناعية والبلدية. نسلّم المواد المناسبة إلى موقع مشروعك." },
  "og.afterSales": { en: "After-Sales Support", ar: "دعم ما بعد البيع" },
  "og.afterSalesDesc": { en: "Our after-sales team provides spare parts supply, equipment servicing, and technical troubleshooting for all equipment we have supplied. We ensure your operations keep running smoothly long after delivery.", ar: "يوفر فريق ما بعد البيع لدينا قطع الغيار وصيانة المعدات والدعم الفني لجميع المعدات التي وردناها. نضمن استمرار عملياتكم بسلاسة بعد التسليم." },
  "og.learnMore": { en: "Learn More →", ar: "← اعرف المزيد" },
  "og.readMore": { en: "Read More →", ar: "← اقرأ المزيد" },

  // Stats
  "og.statMarkets": { en: "Markets", ar: "أسواق" },
  "og.statOffices": { en: "Offices", ar: "مكاتب" },
  "og.statYears": { en: "Years", ar: "سنوات" },
  "og.statProjects": { en: "Projects", ar: "مشاريع" },

  // Case Studies
  "og.caseStudies": { en: "CASE STUDIES", ar: "دراسات حالة" },
  "og.caseHeading": { en: "Projects That Speak for Themselves.", ar: "مشاريع تتحدث عن نفسها." },
  "og.casePipeline": { en: "Pipeline Infrastructure", ar: "البنية التحتية لخطوط الأنابيب" },
  "og.case1Title": { en: "Basra-Amman Pipeline Supply", ar: "توريد خط أنابيب البصرة-عمّان" },
  "og.case1Loc": { en: "Iraq & Jordan — 2024", ar: "العراق والأردن — ٢٠٢٤" },
  "og.case1Desc": { en: "Complete supply of high-grade steel pipes for a cross-border pipeline infrastructure project.", ar: "توريد كامل لأنابيب فولاذية عالية الجودة لمشروع بنية تحتية عابر للحدود." },
  "og.caseRefinery": { en: "Refinery Project", ar: "مشروع مصفاة" },
  "og.case2Title": { en: "Tikrit Refinery Upgrade", ar: "تطوير مصفاة تكريت" },
  "og.case2Loc": { en: "Iraq — 2023", ar: "العراق — ٢٠٢٣" },
  "og.case2Desc": { en: "Equipment supply and technical inspection for a major refinery modernization project.", ar: "توريد معدات وتفتيش فني لمشروع تحديث مصفاة رئيسية." },
  "og.caseExtraction": { en: "Oil Extraction", ar: "استخراج النفط" },
  "og.case3Title": { en: "Southern Iraq Extraction Support", ar: "دعم الاستخراج في جنوب العراق" },
  "og.case3Loc": { en: "Iraq — 2023", ar: "العراق — ٢٠٢٣" },
  "og.case3Desc": { en: "Drilling equipment and after-sales support for extraction operations in southern Iraq.", ar: "معدات حفر ودعم ما بعد البيع لعمليات الاستخراج في جنوب العراق." },
  "og.relatedProjects": { en: "Related Projects", ar: "مشاريع ذات صلة" },
  "og.viewAllCases": { en: "View All Case Studies", ar: "عرض جميع دراسات الحالة" },

  // CTA
  "og.ctaHeading": { en: "Ready to Start Your Next Project?", ar: "مستعد لبدء مشروعك القادم؟" },
  "og.ctaText": { en: "Our team is ready to support your oil and gas requirements across the region.", ar: "فريقنا جاهز لدعم متطلباتكم في مجال النفط والغاز في المنطقة." },
  "og.contactUs": { en: "Contact Us →", ar: "← تواصل معنا" },

  // Key Features
  "og.keyFeatures": { en: "KEY FEATURES", ar: "الميزات الرئيسية" },
  "og.whyChooseUs": { en: "Why Choose Us", ar: "لماذا تختارنا" },

  // Pipes Supply sub-page
  "og.pipesOverviewHeading": { en: "High-Grade Pipes. Delivered to Your Site.", ar: "أنابيب عالية الجودة. تُسلّم إلى موقعك." },
  "og.pipesOverviewText": { en: "AL-JADRIYA Oil & Gas supplies high-grade steel pipes, fittings, and pipeline materials from certified international manufacturers. We source and deliver the right pipe specifications for your project — on time and to standard.", ar: "توفر الجادرية للنفط والغاز أنابيب فولاذية عالية الجودة ووصلات ومواد خطوط الأنابيب من مصنعين دوليين معتمدين. نوفر ونسلّم المواصفات المناسبة لمشروعك — في الوقت المحدد وبالمعايير المطلوبة." },
  "og.pipes.f1.title": { en: "Wide Product Range", ar: "مجموعة منتجات واسعة" },
  "og.pipes.f1.desc": { en: "All diameters, grades, and specifications available", ar: "جميع الأقطار والدرجات والمواصفات متاحة" },
  "og.pipes.f2.title": { en: "Certified Materials", ar: "مواد معتمدة" },
  "og.pipes.f2.desc": { en: "Sourced from internationally certified manufacturers", ar: "من مصنعين معتمدين دولياً" },
  "og.pipes.f3.title": { en: "Flexible Order Sizes", ar: "أحجام طلب مرنة" },
  "og.pipes.f3.desc": { en: "From single shipments to large-scale project supply", ar: "من شحنات فردية إلى توريد مشاريع واسعة النطاق" },
  "og.pipes.f4.title": { en: "On-Time Delivery", ar: "تسليم في الوقت المحدد" },
  "og.pipes.f4.desc": { en: "Reliable logistics to your project site", ar: "خدمات لوجستية موثوقة إلى موقع مشروعك" },

  // Drilling sub-page
  "og.drillingOverviewHeading": { en: "The Right Equipment. Ready When You Need It.", ar: "المعدات المناسبة. جاهزة عندما تحتاجها." },
  "og.drillingOverviewText": { en: "We supply a comprehensive range of drilling equipment and tools to oil and gas operators and contractors across the region. From drill bits and casings to downhole tools and accessories — we source and deliver what your drilling operation requires.", ar: "نورّد مجموعة شاملة من معدات وأدوات الحفر لمشغلي ومقاولي النفط والغاز في المنطقة. من رؤوس الحفر والأغلفة إلى أدوات أسفل البئر والملحقات — نوفر ونسلّم ما تحتاجه عملية الحفر." },
  "og.drilling.f1.title": { en: "Wide Equipment Range", ar: "مجموعة معدات واسعة" },
  "og.drilling.f1.desc": { en: "Drill bits, casings, downhole tools, and accessories", ar: "رؤوس حفر وأغلفة وأدوات أسفل البئر وملحقات" },
  "og.drilling.f2.title": { en: "Global Brands", ar: "علامات عالمية" },
  "og.drilling.f2.desc": { en: "Sourced from world-leading drilling equipment manufacturers", ar: "من أبرز مصنعي معدات الحفر عالمياً" },
  "og.drilling.f3.title": { en: "Full Documentation", ar: "توثيق كامل" },
  "og.drilling.f3.desc": { en: "Certificates, specs, and compliance documents included", ar: "شهادات ومواصفات ووثائق امتثال مرفقة" },
  "og.drilling.f4.title": { en: "Logistics Support", ar: "دعم لوجستي" },
  "og.drilling.f4.desc": { en: "Coordinated delivery to your drill site", ar: "تسليم منسّق إلى موقع الحفر" },

  // Exploration sub-page
  "og.explorationOverviewHeading": { en: "Every Tool Your Survey Team Needs.", ar: "كل أداة يحتاجها فريق المسح." },
  "og.explorationOverviewText": { en: "AL-JADRIYA supplies specialized instruments and equipment for geological surveys, seismic operations, and field exploration programs. We provide the tools — your teams do the work.", ar: "توفر الجادرية أدوات ومعدات متخصصة للمسوحات الجيولوجية والعمليات الزلزالية وبرامج الاستكشاف الميداني. نوفر الأدوات — وفرقكم تنجز العمل." },
  "og.explore.f1.title": { en: "Seismic Instruments", ar: "أدوات زلزالية" },
  "og.explore.f1.desc": { en: "Monitoring and data collection devices for seismic operations", ar: "أجهزة مراقبة وجمع بيانات للعمليات الزلزالية" },
  "og.explore.f2.title": { en: "Survey Equipment", ar: "معدات مسح" },
  "og.explore.f2.desc": { en: "Precision instruments for geological field surveys", ar: "أدوات دقيقة للمسوحات الجيولوجية الميدانية" },
  "og.explore.f3.title": { en: "Field Tools", ar: "أدوات ميدانية" },
  "og.explore.f3.desc": { en: "Portable equipment for on-site exploration work", ar: "معدات محمولة لأعمال الاستكشاف الميداني" },
  "og.explore.f4.title": { en: "Certified Supply", ar: "توريد معتمد" },
  "og.explore.f4.desc": { en: "All instruments sourced from certified manufacturers", ar: "جميع الأدوات من مصنعين معتمدين" },

  // Inspection sub-page
  "og.inspectionOverviewHeading": { en: "Precision Instruments for Quality Control.", ar: "أدوات دقيقة لمراقبة الجودة." },
  "og.inspectionOverviewText": { en: "We supply technical control and inspection instruments used for pipeline quality verification, weld inspection, and field testing. All equipment is sourced from certified manufacturers and delivered with full documentation.", ar: "نورّد أجهزة الرقابة الفنية والتفتيش المستخدمة للتحقق من جودة خطوط الأنابيب وفحص اللحام والاختبارات الميدانية. جميع المعدات من مصنعين معتمدين وتُسلّم بتوثيق كامل." },
  "og.inspect.f1.title": { en: "NDT Equipment", ar: "معدات الاختبار غير الإتلافي" },
  "og.inspect.f1.desc": { en: "Non-destructive testing instruments for quality assurance", ar: "أدوات اختبار غير إتلافي لضمان الجودة" },
  "og.inspect.f2.title": { en: "Weld Inspection Tools", ar: "أدوات فحص اللحام" },
  "og.inspect.f2.desc": { en: "Specialized tools for weld quality verification", ar: "أدوات متخصصة للتحقق من جودة اللحام" },
  "og.inspect.f3.title": { en: "Calibrated Instruments", ar: "أدوات معايرة" },
  "og.inspect.f3.desc": { en: "Factory-calibrated instruments with certification", ar: "أدوات معايرة من المصنع مع شهادات" },
  "og.inspect.f4.title": { en: "Full Documentation", ar: "توثيق كامل" },
  "og.inspect.f4.desc": { en: "Complete certificates and compliance reports provided", ar: "شهادات وتقارير امتثال كاملة مرفقة" },

  // Underground sub-page
  "og.undergroundOverviewHeading": { en: "Materials Built for What Lies Beneath.", ar: "مواد مصنّعة لما يكمن في الأعماق." },
  "og.undergroundOverviewText": { en: "AL-JADRIYA supplies pipes, fittings, and materials used in underground pipeline and infrastructure projects for industrial and municipal applications. We deliver the right materials to your project site.", ar: "توفر الجادرية الأنابيب والوصلات والمواد المستخدمة في مشاريع خطوط الأنابيب والبنية التحتية تحت الأرض للتطبيقات الصناعية والبلدية. نسلّم المواد المناسبة إلى موقع مشروعك." },
  "og.under.f1.title": { en: "Underground-Grade Pipes", ar: "أنابيب لتطبيقات تحت الأرض" },
  "og.under.f1.desc": { en: "Pipes rated for underground conditions and pressure", ar: "أنابيب مصنفة للظروف والضغط تحت الأرض" },
  "og.under.f2.title": { en: "Durable Fittings", ar: "وصلات متينة" },
  "og.under.f2.desc": { en: "Heavy-duty fittings for long-term underground use", ar: "وصلات شديدة التحمل للاستخدام طويل الأمد تحت الأرض" },
  "og.under.f3.title": { en: "Protective Coatings", ar: "طلاءات واقية" },
  "og.under.f3.desc": { en: "Anti-corrosion and protective coating materials supplied", ar: "مواد طلاء مضادة للتآكل وواقية" },
  "og.under.f4.title": { en: "Flexible Supply", ar: "توريد مرن" },
  "og.under.f4.desc": { en: "Adaptable order sizes for any project scale", ar: "أحجام طلب قابلة للتكيف لأي حجم مشروع" },

  // After-Sales sub-page
  "og.afterSalesOverviewHeading": { en: "We Stay With You After Every Delivery.", ar: "نبقى معكم بعد كل تسليم." },
  "og.afterSalesOverviewText": { en: "Our after-sales team provides spare parts supply, equipment servicing, and technical troubleshooting for all equipment we have supplied. We ensure your operations keep running smoothly long after delivery.", ar: "يوفر فريق ما بعد البيع لدينا قطع الغيار وصيانة المعدات والدعم الفني لجميع المعدات التي وردناها. نضمن استمرار عملياتكم بسلاسة بعد التسليم." },
  "og.after.f1.title": { en: "Spare Parts Supply", ar: "توريد قطع الغيار" },
  "og.after.f1.desc": { en: "Fast supply of replacement parts from original manufacturers", ar: "توريد سريع لقطع الغيار من المصنعين الأصليين" },
  "og.after.f2.title": { en: "Equipment Servicing", ar: "صيانة المعدات" },
  "og.after.f2.desc": { en: "Professional servicing for all supplied equipment", ar: "صيانة احترافية لجميع المعدات الموردة" },
  "og.after.f3.title": { en: "Technical Troubleshooting", ar: "استكشاف الأخطاء الفنية" },
  "og.after.f3.desc": { en: "Remote and on-site troubleshooting support available", ar: "دعم استكشاف الأخطاء عن بُعد وفي الموقع" },
  "og.after.f4.title": { en: "Rapid Response", ar: "استجابة سريعة" },
  "og.after.f4.desc": { en: "Priority support for critical operational issues", ar: "دعم ذو أولوية للمشاكل التشغيلية الحرجة" },

  // Medical Company
  "med.medical": { en: "Medical", ar: "الطبية" },
  "med.backToGroup": { en: "← AL-JADRIYA GROUP", ar: "مجموعة الجادرية →" },
  "med.backToGroupShort": { en: "AL-JADRIYA GROUP", ar: "مجموعة الجادرية" },
  "med.brandFull": { en: "AL-JADRIYA MEDICAL", ar: "الجادرية الطبية" },
  "med.footerTagline": { en: "Comprehensive medical engineering solutions across the Middle East.", ar: "حلول هندسة طبية شاملة في الشرق الأوسط." },
  "med.rights": { en: "© 2026 AL-JADRIYA MEDICAL. All rights reserved.", ar: "© ٢٠٢٦ الجادرية الطبية. جميع الحقوق محفوظة." },
  "med.services": { en: "Our Services", ar: "خدماتنا" },

  // Medical Hero slides
  "med.hero1.label": { en: "BIOMEDICAL ENGINEERING", ar: "الهندسة الطبية الحيوية" },
  "med.hero1.heading": { en: "Where Engineering Meets Healthcare.", ar: "حيث تلتقي الهندسة بالرعاية الصحية." },
  "med.hero1.tab": { en: "Biomedical", ar: "الطبية الحيوية" },
  "med.hero2.label": { en: "HOSPITAL EQUIPMENT SUPPLY", ar: "توريد معدات المستشفيات" },
  "med.hero2.heading": { en: "Equipping Healthcare From the Ground Up.", ar: "تجهيز الرعاية الصحية من الأساس." },
  "med.hero2.tab": { en: "Equipment", ar: "المعدات" },
  "med.hero3.label": { en: "CAPACITY MANAGEMENT", ar: "إدارة القدرات" },
  "med.hero3.heading": { en: "Optimizing Every Bed. Every Floor.", ar: "تحسين كل سرير. كل طابق." },
  "med.hero3.tab": { en: "Capacity", ar: "القدرات" },
  "med.hero4.label": { en: "TURNKEY MEDICAL PROJECTS", ar: "مشاريع طبية متكاملة" },
  "med.hero4.heading": { en: "From Blueprint to Fully Equipped.", ar: "من المخطط إلى التجهيز الكامل." },
  "med.hero4.tab": { en: "Turnkey", ar: "متكاملة" },
  "med.hero5.label": { en: "MEDICAL TENDER MANAGEMENT", ar: "إدارة المناقصات الطبية" },
  "med.hero5.heading": { en: "Procurement Done Right.", ar: "مشتريات بالطريقة الصحيحة." },
  "med.hero5.tab": { en: "Tenders", ar: "المناقصات" },
  "med.hero6.label": { en: "AFTER-SALES SUPPORT", ar: "دعم ما بعد البيع" },
  "med.hero6.heading": { en: "Support That Never Stops.", ar: "دعم لا يتوقف." },
  "med.hero6.tab": { en: "Support", ar: "الدعم" },

  // Medical Services section
  "med.whatWeOfferLabel": { en: "WHAT WE OFFER", ar: "ما نقدمه" },
  "med.whatWeOffer": { en: "What We Offer", ar: "ما نقدمه" },
  "med.servicesHeading": { en: "Comprehensive Medical Engineering Solutions.", ar: "حلول هندسة طبية شاملة." },
  "med.biomedical": { en: "Biomedical Engineering", ar: "الهندسة الطبية الحيوية" },
  "med.biomedicalDesc": { en: "Engineering consultancy and technical support for biomedical systems.", ar: "استشارات هندسية ودعم فني لأنظمة الهندسة الطبية الحيوية." },
  "med.equipmentSupply": { en: "Hospital Equipment Supply", ar: "توريد معدات المستشفيات" },
  "med.equipmentSupplyDesc": { en: "Full supply of medical devices from leading international manufacturers.", ar: "توريد كامل للأجهزة الطبية من كبار المصنعين الدوليين." },
  "med.capacityMgmt": { en: "Capacity Management", ar: "إدارة القدرات" },
  "med.capacityMgmtDesc": { en: "Optimize hospital capacity, patient flow, and operational efficiency.", ar: "تحسين سعة المستشفيات وتدفق المرضى والكفاءة التشغيلية." },
  "med.turnkey": { en: "Turnkey Medical Projects", ar: "مشاريع طبية متكاملة" },
  "med.turnkeyDesc": { en: "End-to-end delivery of fully equipped medical facilities.", ar: "تسليم شامل لمرافق طبية مجهزة بالكامل." },
  "med.tenderMgmt": { en: "Medical Tender Management", ar: "إدارة المناقصات الطبية" },
  "med.tenderMgmtDesc": { en: "Expert management of medical procurement tenders.", ar: "إدارة احترافية لمناقصات المشتريات الطبية." },
  "med.afterSales": { en: "After-Sales Support", ar: "دعم ما بعد البيع" },
  "med.afterSalesDesc": { en: "Ongoing technical support and maintenance after every delivery.", ar: "دعم فني مستمر وصيانة بعد كل تسليم." },
  "med.learnMore": { en: "Learn More →", ar: "← اعرف المزيد" },
  "med.readMore": { en: "Read More →", ar: "← اقرأ المزيد" },

  // Medical Stats
  "med.statMarkets": { en: "Markets", ar: "أسواق" },
  "med.statOffices": { en: "Offices", ar: "مكاتب" },
  "med.statYears": { en: "Years", ar: "سنوات" },
  "med.statFacilities": { en: "Facilities Equipped", ar: "منشآت مجهزة" },

  // Medical Case Studies
  "med.caseStudies": { en: "CASE STUDIES", ar: "دراسات حالة" },
  "med.caseHeading": { en: "Projects That Improved Healthcare.", ar: "مشاريع حسّنت الرعاية الصحية." },
  "med.caseHospitalEquip": { en: "Medical Gas Systems", ar: "أنظمة الغازات الطبية" },
  "med.case1Title": { en: "Ana Hospital Medical Oxygen Plant", ar: "محطة أوكسجين طبي في مستشفى عنة" },
  "med.case1Loc": { en: "Anbar, Iraq — IOM Partnership", ar: "الأنبار، العراق — بالتعاون مع المنظمة الدولية للهجرة" },
  "med.case1Desc": { en: "Supply and installation of a medical oxygen generation plant and a 30-cylinder filling system at Ana Hospital in Anbar, in cooperation with the International Organization for Migration (IOM).", ar: "توريد وتركيب محطة توليد أوكسجين طبي ونظام تعبئة ٣٠ أسطوانة في مستشفى عنة بالأنبار، بالتعاون مع المنظمة الدولية للهجرة." },
  "med.caseDiagnostics": { en: "Diagnostic Imaging", ar: "التصوير التشخيصي" },
  "med.case2Title": { en: "Amman Medical Center Imaging Suite", ar: "جناح التصوير في المركز الطبي بعمّان" },
  "med.case2Loc": { en: "Jordan — 2023", ar: "الأردن — ٢٠٢٣" },
  "med.case2Desc": { en: "Turnkey delivery of a radiology department with CT and MRI systems.", ar: "تسليم متكامل لقسم الأشعة مع أنظمة الأشعة المقطعية والرنين المغناطيسي." },
  "med.caseLaboratory": { en: "Laboratory Systems", ar: "أنظمة المختبرات" },
  "med.case3Title": { en: "Regional Lab Automation Project", ar: "مشروع أتمتة المختبرات الإقليمي" },
  "med.case3Loc": { en: "Iraq — 2023", ar: "العراق — ٢٠٢٣" },
  "med.case3Desc": { en: "Automated laboratory systems for high-throughput blood analysis across 3 hospitals.", ar: "أنظمة مختبرات مؤتمتة لتحليل الدم عالي الإنتاجية عبر ٣ مستشفيات." },
  "med.relatedProjects": { en: "Related Projects", ar: "مشاريع ذات صلة" },
  "med.viewAllCases": { en: "View All Case Studies", ar: "عرض جميع دراسات الحالة" },

  // Medical CTA
  "med.ctaHeading": { en: "Ready to Equip Your Facility?", ar: "مستعد لتجهيز منشأتك؟" },
  "med.ctaText": { en: "Our medical engineering team is ready to support your project from planning to delivery.", ar: "فريقنا للهندسة الطبية جاهز لدعم مشروعك من التخطيط إلى التسليم." },
  "med.contactUs": { en: "Contact Us →", ar: "← تواصل معنا" },

  // Medical Key Features
  "med.keyFeatures": { en: "KEY FEATURES", ar: "الميزات الرئيسية" },
  "med.whyChooseUs": { en: "Why Choose Us", ar: "لماذا تختارنا" },

  // Biomedical sub-page
  "med.bioOverviewHeading": { en: "Where Engineering Meets Healthcare", ar: "حيث تلتقي الهندسة بالرعاية الصحية" },
  "med.bioOverviewText": { en: "AL-JADRIYA Medical provides specialized biomedical engineering consultancy to healthcare facilities across the region. Our team supports hospitals and clinics with technical assessments, equipment planning, and engineering solutions that ensure medical systems operate at peak performance. We bridge the gap between clinical needs and technical execution, delivering solutions that directly improve patient care.", ar: "توفر الجادرية الطبية استشارات هندسة طبية حيوية متخصصة للمرافق الصحية في المنطقة. يدعم فريقنا المستشفيات والعيادات بالتقييمات الفنية وتخطيط المعدات والحلول الهندسية التي تضمن عمل الأنظمة الطبية بأعلى أداء." },
  "med.bio.f1.title": { en: "Technical Assessment", ar: "التقييم الفني" },
  "med.bio.f1.desc": { en: "Full evaluation of existing biomedical systems and infrastructure", ar: "تقييم كامل لأنظمة الهندسة الطبية الحيوية والبنية التحتية القائمة" },
  "med.bio.f2.title": { en: "Equipment Planning", ar: "تخطيط المعدات" },
  "med.bio.f2.desc": { en: "Strategic planning for new and replacement medical equipment", ar: "تخطيط استراتيجي للمعدات الطبية الجديدة والبديلة" },
  "med.bio.f3.title": { en: "System Integration", ar: "تكامل الأنظمة" },
  "med.bio.f3.desc": { en: "Ensuring all medical devices work together seamlessly", ar: "ضمان عمل جميع الأجهزة الطبية معاً بسلاسة" },
  "med.bio.f4.title": { en: "Compliance Support", ar: "دعم الامتثال" },
  "med.bio.f4.desc": { en: "Guidance on international biomedical engineering standards", ar: "إرشاد حول معايير الهندسة الطبية الحيوية الدولية" },

  // Equipment Supply sub-page
  "med.equipOverviewHeading": { en: "Equipping Healthcare From the Ground Up", ar: "تجهيز الرعاية الصحية من الأساس" },
  "med.equipOverviewText": { en: "We supply the full range of medical devices and hospital equipment required by modern healthcare facilities. From diagnostic imaging to surgical instruments, AL-JADRIYA Medical sources equipment from certified international manufacturers and manages the complete supply chain from order to installation. Every product we supply meets the highest international quality and safety standards.", ar: "نورّد المجموعة الكاملة من الأجهزة الطبية ومعدات المستشفيات التي تتطلبها المرافق الصحية الحديثة. من التصوير التشخيصي إلى الأدوات الجراحية، تستورد الجادرية الطبية المعدات من مصنعين دوليين معتمدين وتدير سلسلة التوريد الكاملة." },
  "med.equip.f1.title": { en: "Full Range", ar: "مجموعة كاملة" },
  "med.equip.f1.desc": { en: "All medical equipment categories from single source", ar: "جميع فئات المعدات الطبية من مصدر واحد" },
  "med.equip.f2.title": { en: "Certified Brands", ar: "علامات معتمدة" },
  "med.equip.f2.desc": { en: "Sourced from internationally accredited manufacturers", ar: "من مصنعين معتمدين دولياً" },
  "med.equip.f3.title": { en: "Delivery Management", ar: "إدارة التوصيل" },
  "med.equip.f3.desc": { en: "Complete logistics from purchase order to installation", ar: "لوجستيات كاملة من أمر الشراء إلى التركيب" },
  "med.equip.f4.title": { en: "Technical Handover", ar: "التسليم الفني" },
  "med.equip.f4.desc": { en: "Equipment commissioning and staff orientation included", ar: "يشمل تشغيل المعدات وتوجيه الموظفين" },

  // Capacity Management sub-page
  "med.capOverviewHeading": { en: "Optimizing Every Bed. Every Floor.", ar: "تحسين كل سرير. كل طابق." },
  "med.capOverviewText": { en: "Our capacity management service helps healthcare facilities operate more efficiently by analyzing patient flow, bed utilization, and department performance. AL-JADRIYA Medical delivers data-driven strategies that reduce bottlenecks, improve throughput, and maximize the operational capacity of hospitals and clinics without the need for physical expansion.", ar: "تساعد خدمة إدارة القدرات لدينا المرافق الصحية على العمل بكفاءة أكبر من خلال تحليل تدفق المرضى واستخدام الأسرّة وأداء الأقسام. تقدم الجادرية الطبية استراتيجيات مبنية على البيانات لتقليل الاختناقات وتحسين الإنتاجية." },
  "med.cap.f1.title": { en: "Flow Analysis", ar: "تحليل التدفق" },
  "med.cap.f1.desc": { en: "Detailed study of patient movement through the facility", ar: "دراسة مفصلة لحركة المرضى عبر المنشأة" },
  "med.cap.f2.title": { en: "Bed Optimization", ar: "تحسين الأسرّة" },
  "med.cap.f2.desc": { en: "Strategies to maximize bed availability and reduce wait times", ar: "استراتيجيات لزيادة توفر الأسرّة وتقليل أوقات الانتظار" },
  "med.cap.f3.title": { en: "Department Planning", ar: "تخطيط الأقسام" },
  "med.cap.f3.desc": { en: "Reorganization plans for higher operational efficiency", ar: "خطط إعادة تنظيم لكفاءة تشغيلية أعلى" },
  "med.cap.f4.title": { en: "Ongoing Monitoring", ar: "مراقبة مستمرة" },
  "med.cap.f4.desc": { en: "Continuous performance tracking and improvement recommendations", ar: "تتبع مستمر للأداء وتوصيات التحسين" },

  // Turnkey sub-page
  "med.turnkeyOverviewHeading": { en: "From Blueprint to Fully Equipped", ar: "من المخطط إلى التجهيز الكامل" },
  "med.turnkeyOverviewText": { en: "AL-JADRIYA Medical manages the complete delivery of medical facilities, from initial design and procurement through to full equipment installation and handover. Our turnkey service means the client receives a fully operational facility without managing multiple contractors. We coordinate every stage, ensuring quality, timeline, and budget are all met.", ar: "تدير الجادرية الطبية التسليم الكامل للمرافق الطبية، من التصميم الأولي والمشتريات إلى التركيب الكامل للمعدات والتسليم. تعني خدمتنا المتكاملة أن العميل يتسلم منشأة تعمل بالكامل دون إدارة مقاولين متعددين." },
  "med.tk.f1.title": { en: "Single Point", ar: "نقطة واحدة" },
  "med.tk.f1.desc": { en: "One partner managing the entire project lifecycle", ar: "شريك واحد يدير دورة حياة المشروع بالكامل" },
  "med.tk.f2.title": { en: "Design to Delivery", ar: "من التصميم إلى التسليم" },
  "med.tk.f2.desc": { en: "From facility planning through to final commissioning", ar: "من تخطيط المنشأة إلى التشغيل النهائي" },
  "med.tk.f3.title": { en: "Quality Control", ar: "مراقبة الجودة" },
  "med.tk.f3.desc": { en: "Strict oversight at every stage of the project", ar: "رقابة صارمة في كل مرحلة من المشروع" },
  "med.tk.f4.title": { en: "On-Time Handover", ar: "تسليم في الوقت" },
  "med.tk.f4.desc": { en: "Proven track record of delivering on schedule", ar: "سجل حافل في التسليم بالموعد المحدد" },

  // Tender Management sub-page
  "med.tenderOverviewHeading": { en: "Procurement Done Right", ar: "مشتريات بالطريقة الصحيحة" },
  "med.tenderOverviewText": { en: "We manage the full medical procurement tender process for hospitals, government health authorities, and private healthcare groups. AL-JADRIYA Medical handles technical specification writing, vendor evaluation, compliance checking, and contract management — ensuring our clients receive the best equipment at the best value through a fully transparent process.", ar: "ندير عملية مناقصات المشتريات الطبية الكاملة للمستشفيات والهيئات الصحية الحكومية ومجموعات الرعاية الصحية الخاصة. تتولى الجادرية الطبية كتابة المواصفات الفنية وتقييم الموردين وفحص الامتثال وإدارة العقود." },
  "med.tender.f1.title": { en: "Tender Writing", ar: "كتابة المناقصات" },
  "med.tender.f1.desc": { en: "Precise technical specifications for all equipment categories", ar: "مواصفات فنية دقيقة لجميع فئات المعدات" },
  "med.tender.f2.title": { en: "Vendor Evaluation", ar: "تقييم الموردين" },
  "med.tender.f2.desc": { en: "Rigorous assessment of suppliers against quality standards", ar: "تقييم صارم للموردين وفق معايير الجودة" },
  "med.tender.f3.title": { en: "Compliance", ar: "الامتثال" },
  "med.tender.f3.desc": { en: "Full adherence to procurement regulations and guidelines", ar: "الالتزام الكامل بأنظمة وإرشادات المشتريات" },
  "med.tender.f4.title": { en: "Contract Management", ar: "إدارة العقود" },
  "med.tender.f4.desc": { en: "End-to-end oversight from tender to final delivery", ar: "إشراف شامل من المناقصة إلى التسليم النهائي" },

  // After-Sales sub-page
  "med.afterOverviewHeading": { en: "Support That Never Stops", ar: "دعم لا يتوقف" },
  "med.afterOverviewText": { en: "Our after-sales support service ensures every piece of medical equipment we supply continues to perform reliably. We provide maintenance schedules, spare parts supply, technical troubleshooting, and on-site service to keep healthcare facilities running without interruption. Our regional presence means fast response times when it matters most.", ar: "تضمن خدمة دعم ما بعد البيع لدينا أن كل قطعة معدات طبية نوردها تستمر في الأداء بموثوقية. نوفر جداول صيانة وتوريد قطع غيار واستكشاف أخطاء فنية وخدمة في الموقع لإبقاء المرافق الصحية تعمل دون انقطاع." },
  "med.as.f1.title": { en: "Maintenance Plans", ar: "خطط صيانة" },
  "med.as.f1.desc": { en: "Scheduled preventive maintenance for all supplied equipment", ar: "صيانة وقائية مجدولة لجميع المعدات الموردة" },
  "med.as.f2.title": { en: "Spare Parts", ar: "قطع غيار" },
  "med.as.f2.desc": { en: "Rapid supply of genuine replacement parts", ar: "توريد سريع لقطع غيار أصلية" },
  "med.as.f3.title": { en: "On-Site Service", ar: "خدمة في الموقع" },
  "med.as.f3.desc": { en: "Technicians available across Jordan and Iraq", ar: "فنيون متاحون في الأردن والعراق" },
  "med.as.f4.title": { en: "Priority Response", ar: "استجابة ذات أولوية" },
  "med.as.f4.desc": { en: "Fast-track support for critical medical equipment failures", ar: "دعم سريع لأعطال المعدات الطبية الحرجة" },

  // Robotics
  "robo.backToGroup": { en: "← AL-JADRIYA GROUP", ar: "← مجموعة الجادرية" },
  "robo.robotics": { en: "Robotics", ar: "الروبوتات" },
  "robo.hero1.label": { en: "ROBOTICS FOR SCHOOLS", ar: "روبوتات للمدارس" },
  "robo.hero1.heading": { en: "Building Tomorrow's\nEngineers Today.", ar: "نبني مهندسي\nالغد اليوم." },
  "robo.hero1.tab": { en: "Schools", ar: "المدارس" },
  "robo.hero2.label": { en: "AI & PROGRAMMING", ar: "الذكاء الاصطناعي والبرمجة" },
  "robo.hero2.heading": { en: "Code the Future.", ar: "برمج المستقبل." },
  "robo.hero2.tab": { en: "AI & Code", ar: "الذكاء والبرمجة" },
  "robo.hero3.label": { en: "ROBOTICS EQUIPMENT SUPPLY", ar: "توريد معدات الروبوتات" },
  "robo.hero3.heading": { en: "The Right Tools for\nEvery Program.", ar: "الأدوات المناسبة\nلكل برنامج." },
  "robo.hero3.tab": { en: "Equipment", ar: "المعدات" },
  "robo.hero4.label": { en: "CORPORATE TRAINING", ar: "التدريب المؤسسي" },
  "robo.hero4.heading": { en: "Upskill Your Team\nfor the AI Era.", ar: "طوّر فريقك\nلعصر الذكاء الاصطناعي." },
  "robo.hero4.tab": { en: "Corporate", ar: "المؤسسي" },

  "robo.whatWeOfferLabel": { en: "WHAT WE OFFER", ar: "ما نقدمه" },
  "robo.servicesHeading": { en: "Four Programs. One Mission: Building the AI Generation.", ar: "أربعة برامج. مهمة واحدة: بناء جيل الذكاء الاصطناعي." },
  "robo.schoolsName": { en: "Robotics for Schools", ar: "روبوتات للمدارس" },
  "robo.schoolsDesc": { en: "Curriculum-aligned robotics programs delivered directly to schools.", ar: "برامج روبوتات متوافقة مع المنهج تُقدم مباشرة للمدارس." },
  "robo.aiName": { en: "AI & Programming", ar: "الذكاء الاصطناعي والبرمجة" },
  "robo.aiDesc": { en: "Hands-on coding and AI courses for students and professionals.", ar: "دورات برمجة وذكاء اصطناعي عملية للطلاب والمحترفين." },
  "robo.equipmentName": { en: "Robotics Equipment Supply", ar: "توريد معدات الروبوتات" },
  "robo.equipmentDesc": { en: "Professional robotics kits and equipment for any program.", ar: "مجموعات ومعدات روبوتات احترافية لأي برنامج." },
  "robo.corporateName": { en: "Corporate Training", ar: "التدريب المؤسسي" },
  "robo.corporateDesc": { en: "Custom AI and robotics training for organizations at scale.", ar: "تدريب مخصص على الذكاء الاصطناعي والروبوتات للمؤسسات." },
  "robo.learnMore": { en: "Learn More →", ar: "اعرف المزيد ←" },

  "robo.statMarkets": { en: "Markets", ar: "أسواق" },
  "robo.statOffices": { en: "Offices", ar: "مكاتب" },
  "robo.statGraduates": { en: "Graduates", ar: "خريج" },
  "robo.statPartners": { en: "School Partners", ar: "شريك مدرسي" },

  "robo.whoWeServeLabel": { en: "WHO WE SERVE", ar: "من نخدم" },
  "robo.whoWeServeHeading": { en: "Programs Designed for Every Level.", ar: "برامج مصممة لكل مستوى." },
  "robo.serve.schools.title": { en: "Schools", ar: "المدارس" },
  "robo.serve.schools.desc": { en: "Robotics and AI programs for students of all ages, aligned with curriculum.", ar: "برامج روبوتات وذكاء اصطناعي للطلاب من جميع الأعمار، متوافقة مع المنهج." },
  "robo.serve.it.title": { en: "IT Professionals", ar: "محترفو تقنية المعلومات" },
  "robo.serve.it.desc": { en: "Advance your career into artificial intelligence and automation.", ar: "طوّر مسيرتك المهنية نحو الذكاء الاصطناعي والأتمتة." },
  "robo.serve.women.title": { en: "Women in Tech", ar: "المرأة في التقنية" },
  "robo.serve.women.desc": { en: "Dedicated programs supporting women entering the technology sector.", ar: "برامج مخصصة لدعم المرأة في دخول قطاع التكنولوجيا." },
  "robo.serve.institutions.title": { en: "Institutions", ar: "المؤسسات" },
  "robo.serve.institutions.desc": { en: "Large-scale training solutions for organizations and government bodies.", ar: "حلول تدريب واسعة النطاق للمنظمات والهيئات الحكومية." },

  "robo.ctaHeading": { en: "Ready to Launch a Robotics Program?", ar: "مستعد لإطلاق برنامج روبوتات؟" },
  "robo.ctaText": { en: "Our team will design the right program for your school, organization, or institution.", ar: "سيصمم فريقنا البرنامج المناسب لمدرستك أو مؤسستك." },
  "robo.contactUs": { en: "Contact Us", ar: "تواصل معنا" },

  "robo.whatWeOffer": { en: "WHAT WE OFFER", ar: "ما نقدمه" },
  "robo.keyFeatures": { en: "KEY FEATURES", ar: "الميزات الرئيسية" },
  "robo.whyChooseUs": { en: "Why Choose Us", ar: "لماذا نحن" },

  // Schools sub-page
  "robo.schools.overviewHeading": { en: "Robotics Programs for Schools", ar: "برامج الروبوتات للمدارس" },
  "robo.schools.overviewText": { en: "AL-JADRIYA Robotics delivers curriculum-aligned robotics programs directly to schools across Jordan and Iraq. Our programs are designed for students of all ages, from primary through secondary level, using hands-on LEGO and educational robotics kits that make learning engaging, practical, and memorable. We equip schools with the tools, training materials, and certified trainer support needed to run a world-class robotics program.", ar: "تقدم الجادرية للروبوتات برامج روبوتات متوافقة مع المنهج مباشرة للمدارس في الأردن والعراق. برامجنا مصممة للطلاب من جميع الأعمار، من المرحلة الابتدائية حتى الثانوية، باستخدام مجموعات ليغو التعليمية والروبوتات التي تجعل التعلم ممتعاً وعملياً ولا يُنسى." },
  "robo.schools.f1.title": { en: "Curriculum Aligned", ar: "متوافق مع المنهج" },
  "robo.schools.f1.desc": { en: "Programs designed to complement national education standards", ar: "برامج مصممة لتكمل معايير التعليم الوطنية" },
  "robo.schools.f2.title": { en: "All Ages", ar: "جميع الأعمار" },
  "robo.schools.f2.desc": { en: "Tailored content for primary, intermediate and secondary students", ar: "محتوى مخصص لطلاب المراحل الابتدائية والمتوسطة والثانوية" },
  "robo.schools.f3.title": { en: "Full Kit Supply", ar: "توريد كامل" },
  "robo.schools.f3.desc": { en: "LEGO and educational robotics kits provided with every program", ar: "مجموعات ليغو والروبوتات التعليمية مع كل برنامج" },
  "robo.schools.f4.title": { en: "Trainer Support", ar: "دعم المدربين" },
  "robo.schools.f4.desc": { en: "Certified trainers available for on-site delivery and teacher training", ar: "مدربون معتمدون متاحون للتدريب في الموقع وتدريب المعلمين" },

  // AI sub-page
  "robo.ai.overviewHeading": { en: "AI & Programming Courses", ar: "دورات الذكاء الاصطناعي والبرمجة" },
  "robo.ai.overviewText": { en: "Our AI and Programming courses equip students and professionals with practical skills in coding, artificial intelligence, and machine learning. Delivered both in-person at our Amman training center and online, our courses are designed to take learners from beginner level through to advanced AI application development. We focus on real-world projects that build genuine capability and career-ready skills.", ar: "تزود دوراتنا في الذكاء الاصطناعي والبرمجة الطلاب والمحترفين بمهارات عملية في البرمجة والذكاء الاصطناعي والتعلم الآلي. تُقدم شخصياً في مركز التدريب بعمان وعبر الإنترنت، مصممة لنقل المتعلمين من المستوى المبتدئ إلى تطوير تطبيقات الذكاء الاصطناعي المتقدمة." },
  "robo.ai.f1.title": { en: "Beginner to Advanced", ar: "من مبتدئ إلى متقدم" },
  "robo.ai.f1.desc": { en: "Structured learning paths for all experience levels", ar: "مسارات تعلم منظمة لجميع مستويات الخبرة" },
  "robo.ai.f2.title": { en: "Real Projects", ar: "مشاريع حقيقية" },
  "robo.ai.f2.desc": { en: "Hands-on AI and coding projects from day one", ar: "مشاريع ذكاء اصطناعي وبرمجة عملية من اليوم الأول" },
  "robo.ai.f3.title": { en: "In-Person and Online", ar: "حضوري وعن بعد" },
  "robo.ai.f3.desc": { en: "Flexible delivery at our center or remotely", ar: "تقديم مرن في مركزنا أو عن بعد" },
  "robo.ai.f4.title": { en: "Career Ready", ar: "جاهز للعمل" },
  "robo.ai.f4.desc": { en: "Skills aligned with industry demand across the region", ar: "مهارات متوافقة مع طلب السوق في المنطقة" },

  // Equipment sub-page
  "robo.equipment.overviewHeading": { en: "Robotics Equipment Supply", ar: "توريد معدات الروبوتات" },
  "robo.equipment.overviewText": { en: "AL-JADRIYA Robotics supplies professional robotics kits, educational technology equipment, and AI hardware to schools, training centers, and corporate clients across the region. We source from leading international manufacturers and provide technical support to ensure every piece of equipment is deployed and used effectively. Our supply service includes full setup, testing, and trainer orientation.", ar: "توّرد الجادرية للروبوتات مجموعات روبوتات احترافية ومعدات تكنولوجيا تعليمية وأجهزة ذكاء اصطناعي للمدارس ومراكز التدريب والعملاء المؤسسيين في المنطقة. نستورد من أبرز الشركات المصنعة الدولية ونوفر الدعم الفني لضمان نشر واستخدام كل قطعة معدات بفعالية." },
  "robo.equipment.f1.title": { en: "Wide Range", ar: "مجموعة واسعة" },
  "robo.equipment.f1.desc": { en: "Full range of educational and professional robotics equipment", ar: "مجموعة كاملة من معدات الروبوتات التعليمية والاحترافية" },
  "robo.equipment.f2.title": { en: "Certified Brands", ar: "علامات معتمدة" },
  "robo.equipment.f2.desc": { en: "Sourced from internationally recognized manufacturers", ar: "مصدرها من شركات تصنيع معترف بها دولياً" },
  "robo.equipment.f3.title": { en: "Setup Included", ar: "التركيب مشمول" },
  "robo.equipment.f3.desc": { en: "Full installation, testing and configuration on delivery", ar: "تركيب واختبار وتهيئة كاملة عند التسليم" },
  "robo.equipment.f4.title": { en: "Ongoing Supply", ar: "توريد مستمر" },
  "robo.equipment.f4.desc": { en: "Spare parts and upgrade kits available on demand", ar: "قطع غيار ومجموعات ترقية متاحة عند الطلب" },

  // Corporate sub-page
  "robo.corporate.overviewHeading": { en: "Corporate Training Programs", ar: "برامج التدريب المؤسسي" },
  "robo.corporate.overviewText": { en: "We design and deliver custom robotics and AI training programs for companies, government institutions, and large organizations. Our corporate training service begins with a full needs assessment and results in a tailored program that builds real capability within your team. Training can be delivered at your premises, at our Amman center, or online, with flexible scheduling to minimize disruption to operations.", ar: "نصمم ونقدم برامج تدريب مخصصة في الروبوتات والذكاء الاصطناعي للشركات والمؤسسات الحكومية والمنظمات الكبيرة. تبدأ خدمة التدريب المؤسسي بتقييم شامل للاحتياجات وتنتج برنامجاً مخصصاً يبني قدرات حقيقية داخل فريقك." },
  "robo.corporate.f1.title": { en: "Custom Programs", ar: "برامج مخصصة" },
  "robo.corporate.f1.desc": { en: "Training designed specifically around your team's needs", ar: "تدريب مصمم خصيصاً حول احتياجات فريقك" },
  "robo.corporate.f2.title": { en: "Flexible Delivery", ar: "تقديم مرن" },
  "robo.corporate.f2.desc": { en: "On-site, at our center, or online — your choice", ar: "في موقعك، في مركزنا، أو عبر الإنترنت — اختيارك" },
  "robo.corporate.f3.title": { en: "Government Ready", ar: "جاهز للحكومة" },
  "robo.corporate.f3.desc": { en: "Experience delivering programs for public sector institutions", ar: "خبرة في تقديم برامج لمؤسسات القطاع العام" },
  "robo.corporate.f4.title": { en: "Certified Completion", ar: "شهادة إتمام" },
  "robo.corporate.f4.desc": { en: "Participants receive certificates upon program completion", ar: "يحصل المشاركون على شهادات عند إتمام البرنامج" },

  // Featured Projects Section
  "feat.selectedProjects": { en: "SELECTED PROJECTS", ar: "مشاريع مختارة" },
  "feat.trustedRegion": { en: "Trusted Across the Region", ar: "موثوقون في المنطقة" },
  "feat.viewAll": { en: "View All Projects →", ar: "← عرض جميع المشاريع" },
  "feat.ourProjects": { en: "OUR PROJECTS", ar: "مشاريعنا" },
  "feat.medicalExpertise": { en: "Proven Medical Expertise", ar: "خبرة طبية مثبتة" },
  "feat.viewAllMedical": { en: "View All Medical Projects →", ar: "← عرض جميع المشاريع الطبية" },
  "feat.deliveredPrecision": { en: "Delivered with Precision", ar: "تسليم بدقة" },

  // Quote Section
  "quote.text": { en: "He who has health has hope, and he who has hope has everything.", ar: "من كان معافى في بدنه عنده أمل، ومن عنده أمل فعنده كل شيء." },
  "quote.author": { en: "Arabian proverb", ar: "مثل عربي" },

  // References Page
  "ref.trackRecord": { en: "OUR TRACK RECORD", ar: "سجلنا الحافل" },
  "ref.heroHeading": { en: "Our Work Speaks\nfor Itself", ar: "أعمالنا تتحدث\nعن نفسها" },
  "ref.stat1": { en: "50+ Projects", ar: "+٥٠ مشروع" },
  "ref.stat2": { en: "6 Markets", ar: "٦ أسواق" },
  "ref.stat3": { en: "10+ Years", ar: "+١٠ سنوات" },
  "ref.ctaHeading": { en: "Have a Project in Mind?", ar: "هل لديك مشروع في بالك؟" },
  "ref.ctaText": { en: "Our team has delivered 50+ projects across 6 markets. Let us help with yours.", ar: "فريقنا أنجز أكثر من ٥٠ مشروعاً في ٦ أسواق. دعنا نساعدك في مشروعك." },
  "ref.ctaButton": { en: "Get In Touch", ar: "تواصل معنا" },

  // Chatbot
  "chatbot.welcome": { en: "Hello! I'm Jadri, your AL-JADRIYA GROUP assistant. How can I help you today?", ar: "مرحباً! أنا جدري، مساعدك من مجموعة الجادرية. كيف يمكنني مساعدتك؟" },
  "chatbot.placeholder": { en: "Type a message...", ar: "اكتب رسالة..." },
  "chatbot.title": { en: "Jadri — AL-JADRIYA Assistant", ar: "جدري — مساعد الجادرية" },

  // Partners Section
  "partners.heading": { en: "OUR PARTNERS", ar: "شركاؤنا" },
  "partners.sub1": { en: "Trusted by experts.", ar: "موثوقون لدى الخبراء." },
  "partners.sub2": { en: "Working with the best.", ar: "نعمل مع الأفضل." },

  // Parallax CTA
  "cta.heading": { en: "We Deliver Engineering Excellence Across the Region", ar: "نقدم التميز الهندسي عبر المنطقة" },
  "cta.text": { en: "For all your inquiries about our services, get in touch with our team today.", ar: "لجميع استفساراتكم حول خدماتنا، تواصلوا مع فريقنا اليوم." },
  "cta.button": { en: "Contact Us Today →", ar: "← تواصل معنا اليوم" },

  // Company Detail Section
  "detail.oilgas.label": { en: "OIL & GAS", ar: "النفط والغاز" },
  "detail.oilgas.headline": { en: "Supply. Deliver.", ar: "نورّد. نسلّم." },
  "detail.oilgas.body": { en: "AL-JADRIYA Oil & Gas is a specialized supplier of high-grade pipes, drilling equipment, and underground infrastructure solutions. We serve oil and gas operators, contractors, and government projects across Jordan, Iraq, and the wider region. From exploration requirements to after-sales support, we are your single trusted partner in the field.", ar: "الجادرية للنفط والغاز هي مورد متخصص للأنابيب عالية الجودة ومعدات الحفر وحلول البنية التحتية تحت الأرض. نخدم مشغلي النفط والغاز والمقاولين والمشاريع الحكومية في الأردن والعراق والمنطقة الأوسع. من متطلبات الاستكشاف إلى دعم ما بعد البيع، نحن شريككم الموثوق الوحيد في الميدان." },
  "detail.oilgas.button": { en: "Explore Oil & Gas →", ar: "← استكشف النفط والغاز" },

  "detail.medical.label": { en: "MEDICAL", ar: "الطبية" },
  "detail.medical.headline": { en: "Engineering Better Healthcare.", ar: "هندسة رعاية صحية أفضل." },
  "detail.medical.body": { en: "AL-JADRIYA Medical provides comprehensive medical engineering consultancy and full hospital equipment supply to healthcare facilities across the region. From biomedical engineering to complete turnkey hospital projects, we manage every stage of the process — from planning and procurement through to final installation and after-sales support.", ar: "توفر الجادرية الطبية استشارات هندسة طبية شاملة وتوريد كامل لمعدات المستشفيات للمرافق الصحية في المنطقة. من الهندسة الطبية الحيوية إلى مشاريع المستشفيات المتكاملة، ندير كل مرحلة من العملية — من التخطيط والمشتريات حتى التركيب النهائي ودعم ما بعد البيع." },
  "detail.medical.button": { en: "Explore Medical →", ar: "← استكشف الطبية" },

  "detail.robotics.label": { en: "ROBOTICS & AI", ar: "الروبوتات والذكاء الاصطناعي" },
  "detail.robotics.headline": { en: "Shaping the Next Generation.", ar: "نصنع الجيل القادم." },
  "detail.robotics.body": { en: "AL-JADRIYA Robotics delivers world-class robotics and AI education programs to schools, professionals, and institutions across Jordan and Iraq. We supply educational robotics kits, deliver curriculum-aligned programs, and provide corporate training solutions that prepare individuals and organizations for the AI economy.", ar: "تقدم الجادرية للروبوتات برامج تعليم روبوتات وذكاء اصطناعي على مستوى عالمي للمدارس والمهنيين والمؤسسات في الأردن والعراق. نورد مجموعات الروبوتات التعليمية، ونقدم برامج متوافقة مع المناهج، ونوفر حلول تدريب الشركات التي تُعد الأفراد والمنظمات لاقتصاد الذكاء الاصطناعي." },
  "detail.robotics.button": { en: "Explore Robotics →", ar: "← استكشف الروبوتات" },

  "detail.energy.label": { en: "ENERGY", ar: "الطاقة" },
  "detail.energy.headline": { en: "Powering a Cleaner Future.", ar: "نمد مستقبلاً أنظف بالطاقة." },
  "detail.energy.body": { en: "AL-JADRIYA Energy is our clean energy division, currently in development. We are building our capability to deliver solar, wind, and clean energy manufacturing solutions across the region. Our Energy division will bring the same standard of excellence and regional expertise that defines the AL-JADRIYA GROUP to the clean energy sector.", ar: "الجادرية للطاقة هي قسم الطاقة النظيفة لدينا، قيد التطوير حالياً. نبني قدرتنا لتقديم حلول الطاقة الشمسية والرياح وتصنيع الطاقة النظيفة في المنطقة. سيجلب قسم الطاقة لدينا نفس مستوى التميز والخبرة الإقليمية التي تميز مجموعة الجادرية إلى قطاع الطاقة النظيفة." },
  "detail.energy.button": { en: "Coming Soon", ar: "قريباً" },

  // Achievements Section (Homepage)
  "ach.hospitalsNum": { en: "Hospitals Equipped", ar: "مستشفى مجهز" },
  "ach.hospitalsSub": { en: "Across Iraq & Kurdistan", ar: "في العراق وكردستان" },
  "ach.turkishNum": { en: "Beds Across 6 Turkish Hospitals in Iraq", ar: "سرير في ٦ مستشفيات تركية في العراق" },
  "ach.turkishSub": { en: "Fully Equipped by AL-JADRIYA", ar: "مجهزة بالكامل من الجادرية" },
  "ach.devicesNum": { en: "Medical Devices Installed", ar: "جهاز طبي مُركّب" },
  "ach.devicesSub": { en: "Across Jordan, Iraq & UAE", ar: "في الأردن والعراق والإمارات" },
  "ach.contactBtn": { en: "Contact Us Today →", ar: "← تواصل معنا اليوم" },
  "ach.caseStudiesLink": { en: "Check All Case Studies →", ar: "← عرض جميع دراسات الحالة" },

  // Case Studies Page
  "cs.heroTitle": { en: "Our Case Studies & Achievements", ar: "دراسات الحالة والإنجازات" },
  "cs.heroSub": { en: "Real projects. Real impact. Across the region.", ar: "مشاريع حقيقية. أثر حقيقي. في جميع أنحاء المنطقة." },
  "cs.contactSimilar": { en: "Contact Us for a Similar Project →", ar: "← تواصل معنا لمشروع مشابه" },
  "cs.achievementsTitle": { en: "Our Achievements", ar: "إنجازاتنا" },
  "cs.contactProject": { en: "Contact Us for a Similar Project →", ar: "← تواصل معنا لمشروع مشابه" },

  "cs.block1.label": { en: "REHABILITATION PROJECT", ar: "مشروع إعادة تأهيل" },
  "cs.block1.title": { en: "Al-Hussein Teaching Hospital — Al-Samawa", ar: "محافظة سماوة — مستشفى الحسين التعليمي" },
  "cs.block1.location": { en: "Al-Samawa Governorate, Iraq", ar: "محافظة السماوة، العراق" },
  "cs.block1.body": { en: "Complete rehabilitation of Al-Hussein Teaching Hospital, a 500-bed facility in Al-Samawa. The project covered full wall rehabilitation using HPL medical wall panels, crash barriers, and fire and antimicrobial resistant medical doors. Scope also included complete ceiling rehabilitation, full fire suppression system overhaul, complete HVAC system rehabilitation including cooling towers, air distribution systems and ductwork, and full flooring replacement across all departments.", ar: "إعادة تأهيل كاملة لمستشفى الحسين التعليمي، منشأة بسعة ٥٠٠ سرير في السماوة. شمل المشروع إعادة تأهيل الجدران بالكامل باستخدام ألواح HPL الطبية، وحواجز الصدمات، وأبواب طبية مقاومة للحريق ومضادة للميكروبات. كما شمل إعادة تأهيل الأسقف بالكامل، وإصلاح نظام إطفاء الحريق، وإعادة تأهيل نظام التكييف بما في ذلك أبراج التبريد وأنظمة توزيع الهواء والقنوات، واستبدال الأرضيات في جميع الأقسام." },

  "cs.block2.label": { en: "MEDICAL OXYGEN", ar: "أوكسجين طبي" },
  "cs.block2.title": { en: "Ana Hospital Medical Oxygen Plant — Al-Anbar", ar: "محطة أوكسجين مستشفى عانة الطبي — الأنبار" },
  "cs.block2.location": { en: "Al-Anbar Governorate, Iraq · In Partnership with IOM", ar: "محافظة الأنبار، العراق · بالشراكة مع المنظمة الدولية للهجرة" },
  "cs.block2.body": { en: "Supply and installation of a medical oxygen production plant for Ana Hospital in Al-Anbar, with a filling system capacity of 30 cylinders. Project delivered in collaboration with the International Organization for Migration (IOM) to support healthcare infrastructure in underserved areas.", ar: "توريد وتركيب محطة إنتاج أوكسجين طبي لمستشفى عانة في الأنبار، بسعة نظام تعبئة ٣٠ أسطوانة. تم تنفيذ المشروع بالتعاون مع المنظمة الدولية للهجرة لدعم البنية التحتية الصحية في المناطق المحرومة." },

  "cs.block3.label": { en: "WATER INFRASTRUCTURE", ar: "بنية تحتية للمياه" },
  "cs.block3.title": { en: "Baghdad Water Authority — High-Capacity Pumping Station", ar: "هيئة ماء بغداد — محطة ضخ عالية السعة" },
  "cs.block3.location": { en: "Baghdad, Iraq", ar: "بغداد، العراق" },
  "cs.block3.body": { en: "Supply and installation of industrial water pumps for the Baghdad Water Authority, with a total combined capacity of 12,000 cubic meters per hour. Project delivered to support the city's core water distribution infrastructure.", ar: "توريد وتركيب مضخات مياه صناعية لهيئة ماء بغداد، بسعة إجمالية مشتركة تبلغ ١٢٬٠٠٠ متر مكعب في الساعة. تم تنفيذ المشروع لدعم البنية التحتية الأساسية لتوزيع المياه في المدينة." },

  "cs.block4.label": { en: "MEDICAL OXYGEN · 5 HOSPITALS", ar: "أوكسجين طبي · ٥ مستشفيات" },
  "cs.block4.title": { en: "Salah Al-Din Health Directorate — Medical Oxygen Plants", ar: "دائرة صحة صلاح الدين — محطات أوكسجين طبي" },
  "cs.block4.location": { en: "Salah Al-Din Governorate, Iraq", ar: "محافظة صلاح الدين، العراق" },
  "cs.block4.body": { en: "Supply and installation of medical oxygen production plants with a capacity of 42 cubic meters per hour for five hospitals across Salah Al-Din Governorate: Al-Alam Hospital, Balad Hospital, Al-Dhuluiya Hospital, Amerli Hospital, and Al-Dauz Hospital. All five plants were delivered and commissioned as part of a single coordinated project.", ar: "توريد وتركيب محطات إنتاج أوكسجين طبي بسعة ٤٢ متر مكعب في الساعة لخمسة مستشفيات في محافظة صلاح الدين: مستشفى العلم، مستشفى بلد، مستشفى الضلوعية، مستشفى أمرلي، ومستشفى الدوز. تم تسليم وتشغيل جميع المحطات الخمس كجزء من مشروع منسق واحد." },

  "cs.ach1.headline": { en: "Hospitals Equipped", ar: "مستشفى مجهز" },
  "cs.ach1.desc": { en: "Full medical equipment supply including blood refrigerators, ultra-cold freezers (-80°C to -96°C), maternity beds, forensic medicine departments, and dissection tables — across Iraq and Kurdistan.", ar: "توريد معدات طبية كاملة تشمل ثلاجات الدم، والمجمدات فائقة البرودة (-٨٠ درجة إلى -٩٦ درجة مئوية)، وأسرّة الولادة، وأقسام الطب الشرعي، وطاولات التشريح — في العراق وكردستان." },
  "cs.ach2.headline": { en: "Turkish Hospitals Equipped", ar: "مستشفيات تركية مجهزة" },
  "cs.ach2.desc": { en: "Complete turnkey equipment supply for six hospitals with 700 beds each, including blood laboratories, anatomy laboratories, and microbiology laboratories.", ar: "توريد معدات تسليم مفتاح كاملة لست مستشفيات بسعة ٧٠٠ سرير لكل منها، تشمل مختبرات الدم ومختبرات التشريح ومختبرات الأحياء الدقيقة." },
  "cs.ach3.headline": { en: "Al Ain Hospital — UAE", ar: "مستشفى العين — الإمارات" },
  "cs.ach3.desc": { en: "Complete hospital equipment supply in partnership with VAMED, including all patient room refrigeration, laboratory and forensic medicine departments, and hazardous waste treatment.", ar: "توريد معدات مستشفى كاملة بالشراكة مع VAMED، تشمل جميع ثلاجات غرف المرضى، وأقسام المختبرات والطب الشرعي، ومعالجة النفايات الخطرة." },
  "cs.ach4.headline": { en: "Dubai Main Blood Center — UAE", ar: "مركز دبي الرئيسي للدم — الإمارات" },
  "cs.ach4.desc": { en: "Supply of Shouk Freeze plasma blood freezers for the main blood center in Dubai.", ar: "توريد مجمدات بلازما الدم Shouk Freeze لمركز الدم الرئيسي في دبي." },
  "cs.ach5.headline": { en: "Operating Rooms Equipped — Iraq", ar: "غرف عمليات مجهزة — العراق" },
  "cs.ach5.desc": { en: "5 operating rooms for Salah Al-Din Health Directorate and 4 operating rooms for Al-Muthanna Directorate (build and equip).", ar: "٥ غرف عمليات لدائرة صحة صلاح الدين و٤ غرف عمليات لدائرة صحة المثنى (بناء وتجهيز)." },
  "cs.ach6.headline": { en: "Al-Husayniyya — Iraq", ar: "الحسينية — العراق" },
  "cs.ach6.desc": { en: "Complete supply of premature infant (NICU) departments and urodynamics laboratory equipment.", ar: "توريد كامل لأقسام حديثي الولادة الخُدّج (NICU) ومعدات مختبر ديناميكا البول." },

  // Mega Menu Case Studies
  "mega.caseStudies": { en: "Case Studies & Achievements →", ar: "← دراسات الحالة والإنجازات" },

  // Footer
  "footer.ourProjects": { en: "Our Projects", ar: "مشاريعنا" },
};

export const LanguageContext = createContext<LanguageContextType | undefined>(undefined);
